google/android-fhir

- .github/workflows/ci.yml
This fixes issues with Github actions. See this [github blog](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) for details.
This could fix #73.
> Bump emulator runner action version

- build.gradle
- fhirengine/src/test/java/com/google/fhirengine/index/impl/FhirIndexerImplTest.java
With move to Kotlin 1.4, Kotlin itself is able to convert the default observe() to lambada syntax.
> Upgrade to Kotlin Version 1.4

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
This makes it easier for users to implement a new view type: 
1. the user does not need to handle the creation of QuestionnaireItemViewHolder (i.e. they won't be able to make a mistake passing the wrong view)
2. the user does not need to handle the inflation of the layout; it is handled by the factory itself now
Also mark QuestionnaireItemViewHolder, QuestionnaireItemViewHolderFactory#create, QuestionnaireItemAdapter as internal.
> Simplify the view holder factory interface

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItemTest.kt
We had not implemented this because we assumed that it's ok to render the UI without providing an initial value until we implement the initial value to the SDC specification.
However, this already caused issue because the recycler view reuses the questionnaire item views, and if we don't try to set the answer the view might still carry what the user had input for a different question.
> Update the UI using the answers in the view model

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactory.kt
- datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
This is useful when the group isn't used as a header but for logical grouping purposes. In those cases we don't want to end up with a big gap (with height of one text line height).
> Hide group header if the text is empty

- example/src/main/java/com/google/fhirengine/example/PatientListActivity.kt
- example/src/main/java/com/google/fhirengine/example/PatientListViewModel.kt
- example/src/main/java/com/google/fhirengine/example/data/SamplePatients.kt
PatientListActivity observes a MutableLiveData reference, and on change submits the list to the PatientItemRecyclerViewAdapter. The RecyclerViewAdapter only compares and diffs when the list reference being submitted changes, otherwise it doesn't take any action.
Submitting a copy of the list to circumvent the RecyclerViewAdapter optimisation.
Please suggest if there's a better way to handle this.
> Fix for refreshing patient list.

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryInstrumentedTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
- datacapture/src/main/res/layout/questionnaire_item_check_box_view.xml
- datacapture/src/main/res/layout/questionnaire_item_radio_group_view.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderTypeTest.kt
Future work:
- handling the selection of widget type for CHOICE type questions (e.g. radio button group vs drop down) is handled in PR #188 
- handling different answer types besides coding is to be done in a subsequent PR
closing #152
> Create a radio button widget type to handle CHOICE type questions

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryInstrumentedTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryInstrumentedTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextDecimalViewHolderFactoryInstrumentedTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt
- datacapture/src/main/res/drawable/gm_schedule_24.xml
- datacapture/src/main/res/layout/questionnaire_item_date_time_picker_view.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderTypeTest.kt
> Create the widget for date time question type

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> Fixed bug with date and date time widgets where you cannot reenter without moving away 

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
'public' subclass `QuestionnaireItemDropDownViewHolderFactory` exposes its 'internal' supertype `QuestionnaireItemViewHolderFactory`
We make it `internal` to hide the supertype.
> Fix QuestionnaireItemDropDownViewHolderFactory visibility

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
* Spotless - max line length fixed in `QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest`
* Test failures - added test for one decimal place in quantity in questionnaires
> Fix spotless errors and instrumentation tests from #230

- README.md
The Spotless changed its default branch to main from master.
Close https://github.com/google/android-fhir/issues/268
> Update Spotless gradle link with main branch

- core/src/main/java/com/google/android/fhir/db/impl/DbTypeConverters.kt
- core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
@JvmStatic is used for the compiler to generate static methods for Java clients to use. Since internal kotlin classes are never exposed to any users, there's no need to have @JvmStatic annotations on them.
> Remove @JvmStatic annotations in internal classes (not needed for Java interop)

- deps.gradle
- reference/build.gradle
This missing dependency was causing warnings in the activity classes in the reference application.
> Add missing dependency on androidx activity library

- README.md
I have uppercased fhir abbreviation in readme file. Specifically, 
changed this,
> This is the initial demo application for showcasing core SDK features and CQL proof of concept. The demo uses synthea generated data that has been loaded into the HAPI `fhir` server public demo site.
to this,
> This is the initial demo application for showcasing core SDK features and CQL proof of concept. The demo uses synthea generated data that has been loaded into the HAPI `FHIR` server public demo site.
> Uppercased fhir abbreviation in readme

- datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
Quick bug fix which caused last merge to crash when selecting the example with a Questionnaire and Questionnaire response
> Bug fix. Removed hard coded file name from utility function in datacapturegallery/QuestionnaireViewModel.kt

- .github/PULL_REQUEST_TEMPLATE.md
Improve the current PR template to include more guidance and a checklist to help contributors and reviews save time
> Update the PR template to guide contributors

- core/src/main/java/com/google/android/fhir/FhirEngine.kt
- core/src/main/java/com/google/android/fhir/Util.kt
- core/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
- core/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
- core/src/test/java/com/google/android/fhir/UtilTest.kt
Fixes #366
Added basic upload sync API and implementation in `FhirEngine`.
* Sync resources by squashed change type
* Rudimentary check for upload success
Basic feature implemented but needs augmentation to support periodic sync using work manager ala download sync.
**Type**
Feature
**Checklist**
> Add API and implementation for upload sync

- reference/src/main/AndroidManifest.xml
- reference/src/main/res/xml/network_security_config.xml
Fixes #443 
Create network security config xml file in res that allows cleartext traffic in the reference application.
N/A
**Type**
Bug fix
N/A
**Checklist**
> Create network security config that allows cleartext traffic

- datacapture/build.gradle.kts
- engine/build.gradle.kts
Fixes #307 #391 
Maven publish module does not work for the `datacapture` module after the kotlin migration due to missing group ID and version. The `datacapture` module release also misses the source jar.
This PR also adds source jar to the `engine` module release.
N/A
**Type**
Bug fix
N/A
**Checklist**
> Fix maven publish plugin for `datacapture` module and add source jar to `engine` module

- engine/build.gradle.kts
Fixes N/A
Remove FHIR engine's dependency on CQL and bump up version
N/A
**Type**
Releases
N/A
**Checklist**
> Remove FHIR engine's dependency on CQL and bump up version

- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- engine/src/main/java/com/google/android/fhir/db/impl/DbTypeConverters.kt
- engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
- engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
- engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Fixes #283  
- Adds `sort` overload for `NumberClientParam`
- Changes DB `TypeConverter` for `BigDecimal` from `String` to `Double`
- Adds unit test in `SearchTest` to verify output SQL
- Adds integration test in `DatabaseImplTest` to verify ordering when querying the DB
See discussion on #283 for pros and cons of using `Double` instead of using 2 columns for precision + unsigned value.
**Type**
**Checklist**
> Database: Store BigDecimals as doubles (SQLite REAL) instead of Strings

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
Fixes #455
In the `QuestionnaireItemRadioGroupViewHolderFactory` there were two bugs:
1. After the initial selection of the answer, if the user selects a different answer, the change was reflected in the UI but was not reflected in the questionnaireResponseItem. Fixed bug by setting the current answer to the new selected answer
2. When there are more than 1 radio groups in the questionnaire the OnCheckedChangeListener was not being set to null with `radioGroup.removeAllViews()` . This caused the listener to receive a stale value of the questionnaireResponseItem. You can reproduce this by following the instructions in #455 
I selected …
> Radio group bug fix

- engine/src/main/java/com/google/android/fhir/Util.kt
- engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
- engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
… a string value #450
Fixes #450
The issue was related to the default toString() implementation of Address and HumanName model classes in hl7.fhir library.
The approach I have used is to provide asString() extension function for the classes and generate a default comma-separated  string as output.
N.A
**Type**
**Checklist**
> Added extenstions for Address and HumanName models to express them as ..

- datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt
Fixes #477
Data Capture Gallery App crashes when device configuration changes (eg: language is changed and user comes back to the app or Orientation is changed) while user is on Questionnaire Fragment.
The code was replacing the QuestionnaireContainerFragment#arguments with a new Bundle. This caused issue after QuestionnaireContainerFragment#arguments was recreated because of orientation / language change as the navagrs now couldn't get the same data from Bundle as the keys were not there anymore.
Fixing this issue by adding data QuestionnaireContainerFragment#arguments Bundle instead of replacing it with a new one.
**Type**
Choose …
> Fixed crash caused by configuration changes

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/SpotlessConfig.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
- engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
- engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Updates Spotless and ktlint, and re-runs ktlint.
ktlint had a [bug](https://github.com/pinterest/ktlint/issues/729) that results in a cryptic error when attempting to use trailing commas (a valid Kotlin 1.4 feature). Updated ktlint to the latest version. Updated Spotless as well, and ran `spotlessApply` to apply the updated ktlint rules.
**Type**
**Checklist**
> Update Spotless + ktlint to latest versions

- reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt
Fix reference app crash.
Testing
Tested on Moto G5 Plus, Android 8.1
Fixes #565 
Reference app was getting crashed when context was null in ContextWrapper.
Moved init block to onCreate callback method in FhirApplication. 
No
**Type**
**Checklist**
> Reference app get crashed when it get launched.

- .github/workflows/ci.yml
Fixes # trivial
use mac-os version 11.0 to avoid emulator timeout.
see 
current version
https://github.com/google/android-fhir/runs/2888614202 
after using mac-os version 11.0
https://github.com/google/android-fhir/runs/2891412388
see https://github.com/ReactiveCircus/android-emulator-runner/issues/160
**Type**
Choose one:  Other
**Checklist**
> temporarily use mac-os version 11.0 to avoid emulator timeout.

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
Fixes #587 
Removes unused property on questionnaire fragment that causes crash. It incorrectly exposes a property on the view model. If the application needs to access that property for some reason it should always go through the view model rather than trying to access it directly from the fragment.
NA
**Type**
Bug fix
**Checklist**
> Remove property that exposes the questionnaire through fragment

- datacapture/src/main/java/com/google/android/fhir/datacapture/validation/PrimitiveTypeAnswerMaxLengthValidator.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/validation/PrimitiveTypeAnswerMaxLengthValidatorTest.kt
Fixes #616 
Fix NPE
NA
**Type**
**Checklist**
> Fix null pointer exception for max length validator

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
Fixes #652 
Add the answer changed callback to the drop down widget which was previously missing
NA
**Type**
Bug fix
**Checklist**
> Add the answer changed callback to the drop down widget

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
Fixes #652 
- In the questionnaire response item map, we were missing answers to questions nested under other non-group questions. This causes issues for enable when evaluation because no answer can be retrieved to evaluate if another question should be enabled or not
- The assumption that the response item map is immutable needs to be removed. This is because as the user answers questions, more nested items might be created (questions nested under other questions are nested in the response under the answers).
NA
**Type**
Bug fix
**Checklist**
> Add missing nested answers to the questionnaire response item map

- .github/workflows/ci.yml
- README.md
- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Plugins.kt
- engine/build.gradle.kts
Fixes #671 
* Generate coverage reports using built-in jacoco plugin
* Upload report to codecov.io
Coveralls is another coverage report provider but we need add a plugin to upload reports which might impact build times. However this a weak criteria and it should be re-considered.
**Type**
Choose one: Testing
**Checklist**
> Enable coverage on debug builds and upload to codecov

- datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/SimpleWorkerContextProvider.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ShadowNpmPackageProvider.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/SimpleWorkerContextProviderTest.kt
Fixes #666 
Convert ResourceMapper, SimpleWorkerContextProvider and NpmPackageProvider functions to suspend functions
None
**Type**
Feature
None
**Checklist**
> Convert ResourceMapper extract and populate functions to suspend funcs

- reference/src/main/java/com/google/android/fhir/reference/EditPatientViewModel.kt
The EditPatientViewModel was still expecting ResourceMapper.extract to return a resource while the api had changed to return a bundle.
**Fixes** : No issue created
**Type**
Bug fix
**Checklist**
> Edit Patient Save logic fix

- engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
- engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
Fixes : NO issue created
Searchable fields like `Patient.gender` were not getting indexed in the database.
**Type**
**Checklist**
> Added code to generate TokenIndex for fhirType code

- gradle.properties
Ensures that all modules have JVM target 1.8 (eg, you don't get a lint error when using `.forEach` anymore), without having to set the JVM options per-module.
**Type**
**Checklist**
> Enable kotlin.setJvmTargetFromAndroidCompileOptions

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
Fixes #651 
Added the missing call to questionnaireItemViewItem.questionnaireResponseItemChangedCallback when questionnaireItemViewItem.singleAnswerOrNull changes. This callback has to be called to run enableWhen and modify the linkIdMaps
Nope
**Type**
Bug fix 
**Checklist**
> Added missing call to questionnaireItemViewItem.questionnaireResponseItemChangedCallback

- README.md
Fixes #734 
Minor fixes:
* Files navigation on the codecov dashboard does not work. This is due to branch info missing from the badge. Fixed link to code coverage dashboard from coverage badge in README.md.
* Codecov has deprecated bash uploader script (that we are currently using to upload reports). Switched to codecov uploader.
* Updated testing documentation to include coverage target and added instructions to improved coverage.
**Type**
Code health
**Checklist**
>  Fix link to code coverage dashboard in README.md 

- .github/workflows/ci.yml
Reverts google/android-fhir#457
> Revert "chore : Add relevant files to `paths-ignore`"

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
Fixes #736 
Response item change callback was missing on checkbox click event.
No
**Type**
**Checklist**
> Add response item change callback on checkbox click event.

- engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
- engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
Fixes #694 
Resource properties which are in SearchParam reference but are of type Canonical/Uri are now handled and do not throw ClassCastException
No alternates. Ideally the resolved type and the SearchParam definition should have been of different type, but Reference, Canonical and Uri and closely related and handled in same way by hapi-fhir library. So we need to handle the resolved type properly
**Type**
Bug fix
**Checklist**
> Handle Indexing of canonical types and uri types in referenced resources

- engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
- engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
Fixes #768 
Switched HapiWorkerContext with SimpleWorkerContext in the ResourceIndexer. Added necessary unit test.
Additionally, locally tested against large file from [Synthea]( https://synthea.mitre.org/downloads) to make sure indexing works fine.
No
**Type**
**Checklist**
> Fixed crash caused by java.lang.UnsupportedOperationException when evaluating Observation.component.valueQuantity

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #755 
Add response item initial value to questionnaire response only if enablewhen is true.
Remove response item initial value from questionnaire response if enablewhen is false.
**Type**
**Checklist**
> Add response item initial value to questionnaire response only if enablewhen is true.

- reference/src/main/assets/new-patient-registration-paginated.json
Fixes #795 
Earlier sdc library was not supporting hidden extension. Therefore to hide the element enablewhen element was used.
Currently, if element is not enabled then respective questionnaire response item get removed from questionnaire response at the time of request. 
Now, to hide the element hidden extension is used so that response item and initial value will be present in response.
No.
**Type**
**Checklist**
> Use hidden extension to hide the element.

- engine/src/main/java/com/google/android/fhir/db/impl/entities/QuantityIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
- engine/src/main/java/com/google/android/fhir/index/entities/QuantityIndex.kt
- engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
- engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
- engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Fixes #733 
Always canonicalize quantity values in the quantity index table.
**Type**
**Checklist**
> Always canonicalize quantity values

- buildSrc/src/main/kotlin/Dependencies.kt
Fixes #947
Update datastore version from 1.0.0-rc02 to 1.0.0
N/A
**Type**
N/A
**Checklist**
> Update datastore version from 1.0.0-rc02 to 1.0.0 

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/JacocoConfig.kt
Update deprecated jacoco block to testCoverage in build files
NA
**Type**
Code health
**Checklist**
> Update deprecated jacoco block to testCoverage in build files

- engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
Fixes #823
Update and reformat the comment on line 113-130 so the spotlessCheck can converge
The alternative way for fixing this can be: Change the way how spotless handles the comment format. But Spotless is out of our control and the android-fhir project scope.
**Type**
Code health
**Checklist**
> Reformat LocalChangeUtils.kt to avoid spotless divergence

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
Fixes #970 
After analyzing the trace, Added `@UiThreadTest` to the setup for tests where the Layout was getting inflated.
**Type**
**Checklist**
> Fixed failing tests of AutoCompleteTextView for lower android versions.

- workflow/build.gradle.kts
Correct the group id and artifact id of the workflow library
NA
**Type**
NA
**Checklist**
> Correct the group id and artifact id of the workflow library

- buildSrc/src/main/kotlin/Releases.kt
Fixes #1005 
Bump up the version of fhir engine for a new release to resolve #1005.
This issue is partially resolved for data capture library clients who do not depend on earlier versions of fhir engine. However, if developers use an earlier version of fhir engine, a duplicated class exception will be thrown due to the common lib code being part of fhir engine.
The dependency change has already been included in #1017 for the engine library.
**Type**
**Checklist**
> Bump up the version of fhir engine to alpha06

- demo/src/main/assets/new-patient-registration-paginated.json
Fixes #834
Adds missing 'Gender' label to new-patient-registration-paginated.json
**Type**
**Checklist**
> Demo App: Add missing 'Gender' label to Add Patient screen

- demo/src/main/assets/new-patient-registration-paginated.json
- demo/src/main/assets/screener-questionnaire.json
…
Fixes #1029 and #1032 
Based on [Hl7's Definition based extraction guide](http://hl7.org/fhir/uv/sdc/2019May/extraction.html#definition-based-extraction), the itemExtractionContext should be used for creation of resources and definition should be used to fill up the resources with appropriate values.
**Type**
**Checklist**
> Cleaned up the questionnaire json to have either definition or itemExtractionContext for an item.

- catalog/src/main/java/com/google/android/fhir/catalog/QuestionnaireContainerFragment.kt
- codegen/src/main/java/com/google/android/fhir/codegen/SearchParameterRepositoryGenerator.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
- demo/src/main/java/com/google/android/fhir/demo/AddPatientViewModel.kt
- demo/src/main/java/com/google/android/fhir/demo/EditPatientViewModel.kt
- demo/src/main/java/com/google/android/fhir/demo/ScreenerViewModel.kt
- demo/src/main/java/com/google/android/fhir/demo/data/FhirPeriodicSyncWorker.kt
- engine/src/main/java/com/google/android/fhir/FhirServices.kt
**Fixes** 
#1111 
FhirContext.forR4 initializes FhirContext everytime. It is recommended to use Cached version to prevent heavy opertaion everytime 
**Type**
Choose one: ( Code health)
**Checklist**
> Use cached fhir context

- .github/workflows/ci.yml
- buildSrc/src/main/kotlin/Dependencies.kt
> resolve failing CI

- .github/workflows/ci.yml
> Run instrumentation tests on API 30 instead of 29

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/LicenseeConfig.kt
- engine/build.gradle.kts
- workflow/build.gradle.kts
Update the cql evaluator version to 1.4.2 and remove redundant module exclusions.
**NOTE:** junit is downgraded to 4.12 in this PR due to a dependency issue:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':workflow:lintAnalyzeDebug'.
> Could not resolve all files for configuration ':workflow:debugAndroidTestRuntimeClasspath'.
> Could not resolve junit:junit:4.13.
Required by:
project :workflow
> Cannot find a version of 'junit:junit' that satisfies the version constraints:
Dependency path 'android-fhir:workflow:unspecified' --> 'junit:junit:4.13'
Constraint path 'android-fhir:workflow:unspecified' --> …
```
> Update the cql evaluator version to 1.4.2 (and downgrade junit to 4.12)

- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseEncryptionKeyProvider.kt
Fixes #1120
Use a non-empty string for generating the database encryption key. 
Two topics we discussed within the team
1. The database keys are not stored anywhere but rather it is derived by signing a message using a key from Android keystore. Changing the message to be signed means we will not get back the database key which has already been used in apps that have already leverage our database encryption.
We decided not to handle this because our library is still in alpha
2. Allow app developers to specify the message to be signed.
We …
> Use a non-empty message to generate the database encryption key

- CODEOWNERS
Fixes nothing.
Added myself to CODEOWNERS. Also gave in to my OCD and arranged everything alphabetically.
NA
**Type**
Choose one: Other
**Checklist**
> Added myself to the CODEOWNERS

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextStringViewHolderDelegate.kt
Fixes #1176
The other options are we CAP_WORDS and CAP_CHARACTERS.
I think we can have CAP_WORDS for singleline and CAP_SENTENCES for Multiline : /.
**Type**
Choose one: Feature 
**Checklist**
> update flag so that keyboards starts with an upper case letter

- catalog/src/main/res/layout/component_list_fragment.xml
- catalog/src/main/res/layout/landing_page_item.xml
- catalog/src/main/res/values/dimens.xml
Fixes #1112 
Devices with small resolution and dpi/ppi, component grids were overlapping on each other.
Instead of giving hard coded value as per figma, match parent value is provided as width.
**Type**
**Checklist**
> Landing page component overlapping issue.

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Sdk.kt
This is the preperation work for forwad room to 2.4 or higher version.
Since we want to use room 2.4 for supporting UUID type.
Fixes #1179 Forward compileSdk and targetSdk from 30 to 31 for room 2.4 support
**Type**
**Checklist**
> Forward compileSdk and targetSdk from 30 to 31

- catalog/src/main/assets/boolean_choice_questionnaire.json
- datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
- datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
- datacapture/src/main/res/values/attrs.xml
- datacapture/src/main/res/values/styles.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #1113
Nested display item is subtitle text for parent questionnaire item if data type is not group.
If nested display item is identified as subtitle text, then do not create questionnaire state for it.
Use boolean choice view for end to end use case.
**Type**
**Checklist**
> Nested display item text as subtitle text.

- buildSrc/src/main/kotlin/Dependencies.kt
Fixes #1236 
Upgrade workmanager runtime version to 2.7.1 and desugar lib to 1.1.5
NA
**Type**
**Checklist**
> Upgrade workmanager runtime version to 2.7.1 and desugar lib to 1.1.5

- buildSrc/src/main/kotlin/Dependencies.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/DateIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/DateTimeIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/NumberIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/PositionIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/QuantityIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/ReferenceIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/StringIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/TokenIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/UriIndexEntity.kt
Use UUID type of resourceUUID
Fixes #1218
Use the newest room version of 2.4.2 for UUID type support.
Change the resourceUUID from String type to UUID type.
**Type**
Code health
**Checklist**
> Use newest room version of 2.4.2

- demo/src/main/java/com/google/android/fhir/demo/EditPatientViewModel.kt
- demo/src/main/java/com/google/android/fhir/demo/PatientDetailsViewModel.kt
- engine/src/main/java/com/google/android/fhir/FhirEngine.kt
- engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
- engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
- engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
- workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
Fixes #784 
Use reified generics in the delete and read APIs in FhirEngine.
For example,
```
fhirEngine.load(Patient::class.java, patientId)
```
becomes
```
fhirEngine.get<Patient>(patientId)
```
and
```
fhirEngine.remove(Patient::class.java, patientId)
```
becomes
```
fhirEngine.delete<Patient>(patientId)
```
The implementation uses `inline` functions with `reified` generics, and we use the `@Deprecated` annotation to suggest replacement if the caller accidentally calls the internal APIs.
NA
**Type**
NA
**Checklist**
> Use reified generics for delete and read operations in FhirEngine

- .github/workflows/ci.yml
Fixes #1254 
Split instrumentation test into smaller pieces (one for each lib) to avoid timeout
See #1254 for different options to get to problem
**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | **Builds** | Releases | Other)
**Checklist**
> Fix CI pipeline

- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- engine/src/main/java/com/google/android/fhir/FhirEngine.kt
- engine/src/main/java/com/google/android/fhir/MoreResources.kt
- engine/src/main/java/com/google/android/fhir/db/Database.kt
- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
- engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
- engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
- engine/src/test/java/com/google/android/fhir/MoreResourcesTest.kt
Fixes #1277 
Have the following APIs instead:
```
suspend fun create(vararg resource: Resource): List<String>
suspend fun get(type: ResourceType, id: String): Resource
suspend fun update(vararg resource: Resource)
suspend fun delete(type: ResourceType, id: String)
```
**Type**
**Checklist**
> Use ResourceType for FHIR Engine data access APIs

- datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDate.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
- datacapture/src/main/res/layout/questionnaire_item_date_picker_view.xml
- datacapture/src/main/res/layout/questionnaire_item_date_time_picker_view.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
Date and Time Picker and Input Widget related issues fixed
1. Time and Date Icon shifted to end of input widget
2. replaced setOnFocusChangeListener with setEndIconOnClickListener
**Type**
**Checklist**
> Date and Time Picker and Input Widget related issues fixed

- buildSrc/src/main/kotlin/Dependencies.kt
- datacapture/build.gradle.kts
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
Fixes #940 
add an empty option for the dropdown widget.
**Type**
Choose one: Feature 
**Checklist**
> Add empty option to drop down widget

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/OptionSelectDialogFragment.kt
- datacapture/src/main/res/layout/questionnaire_item_option_item_other_text.xml
Fixes #1293
Android was preventing keyboard to show up in `EditText` inside a `RecyclerView` in a `AlertDialog`. 
Changes done are as: 
1. Clear dialog windows flags to allow keyboard to show up. (see https://stackoverflow.com/a/9118027)
2. Adjust soft input mode for Dialog to resize itself when keyboard shows up so that the Ok-Cancel buttons are visible.
3. Moved the input `EditText` to `TextInputLayout` .
4. Fixed deleteButton by adding tint color so that it is visible in all the applied themes.
5. Moved from default `AlertDialog.Builder` to `MaterialAlertDialogBuilder`.
Have you considered any alternatives? And if so, why have you …
> Fixed keyboard now showing up in open-choice dialog.

- datacapture/src/main/res/layout/questionnaire_item_date_picker_view.xml
- datacapture/src/main/res/layout/questionnaire_item_date_time_picker_view.xml
Fixes #1292 
Remove error for input field in Date and DateTime pickers
NA
**Type**
Bug fix
**Checklist**
> Remove error for input field in Date and DateTime pickers

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
…
Set `EditText's inputType to InputType.TYPE_NULL`.   In xml files, we couldn't use `android:editable` because it is deprecated and recommended `android:inputType="none"`  doesn't work unless we use `android:focusable="false"` as well but it causes the text cursor to show up for a split second. 
Alternatively we could fix the format in which the date or time is entered in to EditText. But that may need some input from UX team and more work on maybe creating a custom date input edit text.
**Type** …
> Stoping users from being able to input/edit date or time in the respective viewholders.

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
`QuestionnaireItemDropDownViewHolderFactoryEspressoTest#shouldSetDropDownValueToAutoCompleteTextView`
Fixes #1323 
- Temporarily disable `QuestionnaireItemDropDownViewHolderFactoryEspressoTest#shouldSetDropDownValueToAutoCompleteTextView`
- Improve imports
- Use property access syntax
- Remove unnecessary explicit type arguments
NA
**Type**
Testing
NA
**Checklist**
> Temporarily disable QuestionnaireItemDropDownViewHolderFactoryEspressoTest

- .github/workflows/ci.yml
Fixes #1320 
Add `if: always()` to the step of zipping build files
NA
**Type**
Builds
**Checklist**
> Add `if: always()` to the step of zipping build files

- workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
Temporarily fixes #1336 
Disable workflow unit test that fails with OOM
Disable the test temporarily to allow PRs to be merged. We will re-enable the test once the OOM issue is resolved.
**Type**
Testing
NA
**Checklist**
> Disable workflow unit test that fails with OOM

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/AutoCompleteTextViewAction.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
Fixes #1323
**Type**
**Checklist**
> Add 100ms delay to the AutoComplete action in emulator tests to fix the test flakiness

- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextDecimalViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextMultiLineViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryTest.kt
Fixes #1330 
Make SDC library widget tests use Robolectric
NA
**Type**
Testing
NA
**Checklist**
> Make SDC library widget tests use Robolectric

- common/build.gradle.kts
QuickFix :Common should not depend on JUnit
**Type**
Bug fix | Testing
**Checklist**
> QuickFix :Common should not depend on JUnit

- datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDateTimesTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDatesTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
Changed Date format from `MEDIUM (e.g. Oct 18, 2010 )` to `SHORT (e.g. 10/18/10)`
**Type**
**Checklist**
> Date changed to short format instead of default (medium)

- engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
Disable SyncJobTest that fails
NA
**Type**
Testing
**Checklist**
> Disable SyncJobTest that fails

- buildSrc/src/main/kotlin/Dependencies.kt
> Update the common library dependency version to 0.1.0-alpha03

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/AutoCompleteTextViewAction.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> Fix extraction for choice type values

- buildSrc/src/main/kotlin/Dependencies.kt
Fixes #1012 
Update material design dependency version to 1.6.0 to setup precondition to migrate from material design 2 to material design 3 (you).
**Type**
**Checklist**
> Update material design dependency version to 1.6.0

- catalog/src/main/assets/default_layout_questionnaire.json
- catalog/src/main/res/values/styles.xml
Fixes #1362 
`TextAppearance.MaterialComponents.Subtitle2` has medium font weight but it does not have font size 16 sp. 
Inherit Subtitle2 font instead of Subtitle1 and override textSize with 16 sp value.
With this change it is not required to add roboto font with medium font weight separately.
https://github.com/google/android-fhir/pull/1364
**Type**
**Checklist**
> Update medium font.

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Plugins.kt
- buildSrc/src/main/kotlin/RulerConfig.kt
- catalog/build.gradle.kts
- demo/build.gradle.kts
Adds `:analyzeDebugBundle` and `:analyzeReleaseBundle` tasks, which generate
HTML and JSON reports detailing the size breakdown of various libraries
in an app.
For example, Ruler reports that mlkit adds ~13.4MB to the demo app install-size, and ~7.3MB to its download-size
**Type**
Choose one: (Code health)
**Checklist**
> Add spotify/ruler plugin

- buildSrc/src/main/kotlin/Releases.kt
- common/build.gradle.kts
- datacapture/build.gradle.kts
- engine/build.gradle.kts
- workflow/build.gradle.kts
Eliminates duplicated, complex logic across `build.gradle.kts` library files.
Tested by verifying `./gradlew :engine:publishToMavenLocal` runs successfully
**Type**
Choose one: (Code health)
**Checklist**
> Pull Maven publish logic up into a buildSrc helper

- catalog/src/main/res/values-night/themes.xml
- catalog/src/main/res/values/colors.xml
- catalog/src/main/res/values/styles.xml
- catalog/src/main/res/values/themes.xml
Fixes #1424 
Existing catalog app codebase referring material 2 color theme.
It is required to update color theme as per material 3.
**Type**
**Checklist**
> Update theme/colors to Material 3.

- engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
Temporarily disable "sync time should update on every sync call" test
NA
**Type**
Bug fix
NA
**Checklist**
> Temporarily disable "sync time should update on every sync call" test

- buildSrc/src/main/kotlin/Dependencies.kt
- datacapture/build.gradle.kts
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
Fixes #1427
Add modification count in the state flow in order for the flow to trigger an update
Also make it thread-safe by calling the `update` function instead of directly incrementing the value
cc @joiskash @aurangzaibumer 
NA
**Type**
Bug fix
NA
**Checklist**
> Add modification count in the state flow and make it thread-safe

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
Fixes #1345
See FHIR spec for how EnableWhen should work: https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.enableWhen.question
In this PR:
- added a pre-order trace to keep track of questionnaire response items in pre-order
- added a parent map to track questionnaire response items' parents
- in the logic to find questionnaire response item of a certain linkId, try to find ancestor first (using the parent map), then find the nearest item preceding the item, and then the nearest item succeeding the item (using the pre-order trace)
The current approach uses a map from link id to questionnaires. But this might …
> Rewrite logic to find questionnaire item for EnableWhen evaluation

- .github/workflows/ci.yml
- .github/workflows/deviceTests.yml
- build.gradle.kts
- datacapture/src/main/res/layout/questionnaire_item_multi_select_dialog.xml
- datacapture/src/main/res/values/strings.xml
- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- kokoro/README.md
- kokoro/gcp_ubuntu/common.cfg
- kokoro/gcp_ubuntu/continuous.cfg
- kokoro/gcp_ubuntu/kokoro_build.sh
- kokoro/gcp_ubuntu/presubmit.cfg
- settings.gradle.kts
- testing/build.gradle.kts
Use Kokoro as a CI Tool. 
It is a script-based, meaning that developers can run the `build.sh` script locally to see if there PRs will build and pass when run against Kokoro.
The tool completes its run in 30 minutes, halving the time from GitHub
Also added a `--record_screen` flag to `build.sh` so that users can record their screen locally when testing.
When Kokoro runs, it always adds this flag and uploads the screen capture as part of the artefacts it uploads. The artefacts also include the build logs, the `ci-repo` directory, the `build.zip` file, and any `xml` files from testing
I have kept the GitHub Actions config for now, and think we should use both CI tools for the time being, just for people to become familiar with Kokoro. We can migrate to using only Kokoro in a few weeks.
> Try Kokoro as CI Tool

- datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/QuestionnaireItemPhoneNumberViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextDecimalViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextMultiLineViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextStringViewHolderDelegate.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
- datacapture/src/main/res/layout/questionnaire_item_edit_text_multi_line_view.xml
- datacapture/src/main/res/layout/questionnaire_item_edit_text_single_line_view.xml
- datacapture/src/main/res/layout/questionnaire_item_edit_text_view.xml
Fixes #1197 
Set a minimum number of lines for the multi-line edit text widget.
The widet will initially have 3 lines to indicate that the widget itself supports multi-line input. But as the user types the widget would expand vertically to accommodate more lines.
NA
**Type**
Bug fix
https://user-images.githubusercontent.com/28757340/181742578-fd3373ba-6774-4718-a24e-16ce501a0aaa.mp4
**Checklist**
> Make multi-line text widget taller by default

- buildSrc/src/main/kotlin/Releases.kt
Bump up the sdc library version to 0.1.0-beta04
NA
**Type**
Releases
NA
**Checklist**
> Bump up the sdc library version to 0.1.0-beta04

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
Fixes #1554 
A change in the dropdown answer triggers bindView to be called on the `ViewHolder` again. Since the `adapter` is already set on the `autoCompleteTextView`, this causes the dropdown to appear again as soon as the text is set to it.
Issue is fixed by setting a `null adapter` in the `bindView` before setting text so that any old adapter from previous binding is gone.
**Type**
[drop_down.webm](https://user-images.githubusercontent.com/18224849/185599805-d327c68a-8ab7-44dc-bbea-02b7199 …
> Fix for dropdown showing up again on answer change.

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
Fixes #1542 
1. App crash on drop down item re-selection with valueString as Answer option
2. 2. test cases added for same
**Type**
**Checklist**
> drop down item with valueString answer options selection crash fixed

- workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineLibraryContentProvider.kt
Fixes #1566
This PR fixes obscure NullPointerException when loading and compiling dependent libraries of a library. The Workflow's LibraryContentProvider must return `null` if the library isn't found (as opposed to triggering an NPE) to allow the next providers to continue the process. 
Any exception inside the compilation workflow returns an internal error. 
No
**Type**
Bug Fix
**Checklist**
> NullPointerException inside LibraryContentProvider breaks the compiler's workflow

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
Fixes #1521
answersChangedCallback was not called as local variable of class QuestionnaireItemViewItem "answers" was updated incorrectly. 
Now updated "answers" field by using setAnswer() method to fix it
**Type**
**Checklist**
> Set answer properly to radio button input

- demo/src/main/assets/screener-questionnaire.json
- demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
- demo/src/main/res/values/strings.xml
Fixes #1151
1. prior-edit entry mode added in screener questionnaire to validate required fields
2. removed duplicate required = true field for a questionnaire item causing error message displayed twice on screen for that item
3. removed duplicate string from Demo app string.xml
**Type**
**Checklist**
> prior-edit entry mode added in screener questionnaire

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
Fixes #1580 
**Cause:** 
The date and date time view holders only set text to the TextInput if it was empty before. This logic is required when answer update causes an update in the adapter and subsequent bindView on the ViewHolder.
But, this causes issue when the ViewHolder is recycled for a new QuestionnaireItem and the ViewHolder retains the old text (date).
**Fix:**
Cleanup up the the ViewHolder state when bind is called for a different QuestionnaireItem.
**UPDATE**
As per discussion with @jingtang10 , instead of cleaning state using a hack, `isTextUpdateRequired` is added to the particular `QuestionnaireItemViewHolderDelegate`s to check if textview has to be …
> Clearing the old state of date and date-time ViewHolders

- workflow/testdata/group-measure/patients-bundle.json
Fix the test data, while searching how to fix the test in a sustainable way. 
**Type**
**Checklist**
> Quick fix for the FhirOperator test

- buildSrc/src/main/kotlin/Dependencies.kt
- datacapture/build.gradle.kts
Update HAPI structures lib version to 6.0.1
NA
**Type**
Builds
**Checklist**
> Update HAPI structures lib version to 6.0.1

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #1633 
Fix logic to copy questionnaire response item by matching the ID
NA
**Type**
Bug fix
**Checklist**
> Fix logic to copy questionnaire response item by matching the ID

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #1664 
The problem is that the `getEnabledResponseItems` function does not match questionnaire items and questionnaire response items by linkId. As a result if there is any missing items in the questionnaire response the entire enablement calculation gets out of sync. The fix in this PR is to match them by linkId before doing any enablement calculation.
- Match questionnaire items and questionnaire response items by link id
- Test case for it
- Group questionnaire view model test cases
NA
**Type**
Bug fix
**Checklist**
> Match questionnaire items and questionnaire response items by link id

- datacapture/src/main/res/values/styles.xml
Fixes #1592
Material3 style is applied to the chip in autocomplete view.
**Type**
**Checklist**
> Update material3 chip style.

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/EspressoUtilities.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryEspressoTest.kt
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMultiSelectHolderFactoryInstrumentedTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogSelectViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItemTest.kt
Fixes #1640 
We should not be updating the answers in the questionnaire item view item. The questionnaire item view item should be a read-only model of what the UI should display. Update of the questionnaire item view item should be solely handled by the view model.
**Type**
Bug fix
**Checklist**
> Stop updating answer in questionnaire item view item

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
Fixes #1683 
1. Confirmed that the selected answer is not lost / overriden.
2. Setting checked state on `RadioButton` in `RadioGroup` is sometimes causing the `RadioButton` to not show appropriate state.
3. Fixed by setting state using  `RadioGroup`'s `check` api instead.
**Type**
_Before the fix:_
[boolean_answer.webm](https://user-images.githubusercontent.com/18224849/198580038-6a09d520-fd69-4feb-826d-915833162215.webm)
_After the fix:_ …
> Fix for radio button getting unchecked after scroll (view recycled) in recycler view

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
- datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
- datacapture/src/main/res/layout/questionnaire_item_checkbox_group_view.xml
- datacapture/src/main/res/layout/questionnaire_item_header.xml
- datacapture/src/main/res/layout/questionnaire_item_radio_group_view.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt
Fixes #1586
Show an error text at the top for view Single choice, Boolean choice, Multiple choice.
**Type**
**Checklist**
> Show an error at the top for boolean, single and multiple choice view.

- build.gradle.kts
- buildSrc/src/main/kotlin/Releases.kt
Fixes #1701 
Remove the need for two `afterEvaluate` blocks as one was giving precedence over another, stopping the appending of the build id to the artifacts.
This fix allows developers to follow:
https://github.com/google/android-fhir/wiki/Contributing#use-unreleased-github-build-for-developmenttesting-only
es? And if so, why have you chosen the approach in this PR?
**Type**
**Checklist**
> Append build id to artifact version when built via GH Actions

- catalog/src/main/assets/repeated_group_questionnaire.json
- catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
- catalog/src/main/res/menu/component_menu.xml
- catalog/src/main/res/values/strings.xml
- datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactory.kt
- datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
- datacapture/src/main/res/values/strings.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryTest.kt
Fixes #726 
Adds support for repeated groups.
Also added a sample form that uses repeated groups to record multiple COVID vaccine doses.
Several features are still missing. Given the size of this PR, it seems better to add those features in a follow-up. Most of those features would involve a header per instance of the repeated group which would allow for:
- Expanding/collapsing that instance of the group (via a caret button, using the .isHidden extension, maybe?)
- Deleting that instance of the group (via an X button)
- Labeling that instance of the group with its index
- Better visual clarity of where one group instance ends and the next starts
**Alternative(s) …
> Repeated groups

- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelParameterizedTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
- demo/src/main/java/com/google/android/fhir/demo/AddPatientViewModel.kt
- demo/src/main/java/com/google/android/fhir/demo/MainActivity.kt
- demo/src/main/java/com/google/android/fhir/demo/PatientDetailsFragment.kt
- demo/src/main/java/com/google/android/fhir/demo/PatientDetailsViewModel.kt
- demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
At the moment all test cases in `QuestionnaireViewModel.kt` are being run 4 times with the permutations of providing the questionnaire and the questionnaire response using string or URL.
This is highly inefficient and unnecessary. In fact, we only need to have a few test cases to check the mechanism to load the questionnaire and questionnaire response is working with both string and URL. The test cases regarding other parts of the view model logic shouldn't need to be run 4 times each.
NA
**Type**
Testing
**Checklist**
> Separate the parameterized tests for questionnaire view model

- implementationguide/build.gradle.kts
- implementationguide/src/androidTest/java/com/google/android/fhir/implementationguide/db/impl/ImplementationGuideDatabaseTest.kt
- implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/DbTypeConverters.kt
- implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/ImplementationGuideDatabase.kt
- implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/dao/ImplementationGuideDao.kt
- implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ImplementationGuideEntity.kt
- implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ResourceEntity.kt
- implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ResourceMetadataEntity.kt
Issue https://github.com/google/android-fhir/issues/1729
Add a DB to store metadata for 
For the first iteration, complex structure of indices (like in `FHIREngine` is not necessary - most of the resources we are interested in for now are Libraries and ValueSets that are looked up by id, name or uri. 
**Type**
Feature
**Checklist**
> Add db layer for storing metadata for Ig library

- datacapture/build.gradle.kts
- engine/build.gradle.kts
- implementationguide/build.gradle.kts
- workflow/build.gradle.kts
In order to facilitate building documentation during the release process, @jingtang10 wants to have versioned documentation. This PR adds an additional directory of the current version number.
Continuing to use unversioned docs. Less preferable as it complicates the order of operations during a release.
**Type**
Documentation
**Checklist**
> Add version to output path for Dokka

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/QuestionnaireItemPhoneNumberViewHolderFactoryInstrumentedTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireAdapterItem.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapter.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemReviewAdapter.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapterTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemReviewAdapterTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #1766 
This is a sealed class that currently only has one subtype, wrapping `QuestionnaireItemViewItem`.
More subtypes will be added in the future to support (for example) repeated group headers, allowing us to break from the current 1:1 mapping of question:row in our adapters.
`QuestionnaireItemEditAdapter` and `QuestionnaireItemReviewAdapter` were changed to use this new type.
Discussed in Eng Weekly, this is the best approach
**Type**
Code health
**Checklist**
> Introduce new `QuestionnaireAdapterItem` type

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryTest.kt
Fixes #1818 
1. Remove any previous changes listener so that the initialisation doesn't cause a side effect.
2. Added appropriate unit tests.
No
**Type**
**Checklist**
> Cleanup the state of SliderViewHolder when item is recycled.

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireFragmentTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #1817
1. Make submit button Visible in Review mode if the app is using the inbuilt submit button.
2. Updated `QuestionnaireValidationErrorMessageDialogFragment` and `QuestionnaireFragment` to pass in appropriate result messages in callback to change mode from Review to Edit incase there are errors on Submit and user decides to fix them.
No
**Type**
[review_mode_edit.webm](https://user-images.githubusercontent.com/18224849/214304944-d5fd066d-a9f8-4626-91a8-d5fe219b8843.webm)
**Checklist**
> Show submit button in review mode.

- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
Fixes #1825
Issue: Updating resource via `FhirEngine.update ` api doesn't delete previous indexes.
Solution: In the database, for the `ResourceEntity` do `Insert` instead of `Update` as it results in the Deletion of old `ResourceEntity` (based on ConflictStrategy) that causes of its `IndexEntities` to get deleted as well based on their `ForeignKey` constrain.
The other approach is to have a `Unique Index` for each IndexEntity that will Delete it based on the `insert*Index`'s `OnConflictStrategy`. 
Proposed solution is inline with how we handle …
> Fix for removing old indexes when resource is updated

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/FirebaseTestLabConfig.kt
- buildSrc/src/main/kotlin/JacocoConfig.kt
- buildSrc/src/main/kotlin/Plugins.kt
- datacapture/build.gradle.kts
- engine/build.gradle.kts
- kokoro/gcp_ubuntu/kokoro_build.sh
- workflow/build.gradle.kts
* Move firebase test lab setup from running in script to being a Gradle config
* Using new method fixes upload error Codecov used to face when adding instrumentation tests
* Codecov could not parse coverage.ec returned via gcloud, but does so now when run from gradle
**Type**
**Checklist**
> Get code coverage working again

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/common/datatype/MoreTypes.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDateTimes.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
- datacapture/src/main/res/values/strings.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireResponseItemAnswerComponentTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDateTimesTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDatesTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
Fixes #1802
1. Fixed date format error message was visible after entering valid date which was partial answer in  QuestionnaireItemDateTimePickerViewHolderFactory.
2. isAndroidIcuSupported check is removed as 24 min API level is supported
3. Figure out separator from date pattern
4. Generate new date format have 2 digits for day and month, 4 digits for year mandatory.
5. Automatically date separator are added between day month year
6.  Change made to always get the latest value from Locale.getLocale()  
7. before setting date to editText from questionnaire answer , it is formatted to acceptable format having 2 digits for day and month, 4 digits for year mandatory …
> Automatically add date separator between day month year

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #1845
Added `EXTRA_SHOW_SUBMIT_BUTTON` to show or hide submit button in a `QuestionnaireFragment`. Default is `True` (show).
Also, removed any dependence on `Questionnaire.SubmitButtonStyle`  to show or hide submit button in a `QuestionnaireFragment`. 
**Type**
Choose one:  Feature
**Checklist**
> Questionnaire Fragment: Added extra to show or hide submit button.

- catalog/src/main/java/com/google/android/fhir/catalog/CustomQuestionnaireFragment.kt
- catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireFragmentTest.kt
- demo/src/main/java/com/google/android/fhir/demo/AddPatientFragment.kt
- demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
- demo/src/main/java/com/google/android/fhir/demo/ScreenerFragment.kt
Fixes #1848
1. Added Builder to QuestionnaireFragment so that the application developers don't have to lookup appropriate keys for Bundle args.
2. Made QuestionnaireFragment closed and added `QuestionnaireItemViewHolderFactoryMatchersProvider` and `QuestionnaireItemViewHolderFactoryMatchersProviderFactory` that can now be used by application developers to add custom `QuestionnaireItemViewHolderFactory` to the questionnaire.
**Type**
Choose one:   Code health 
**Checklist**
> Added Builder to Questionnaire Fragment.

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
Added `setShowSubmitButton` to the `QuestionnaireFragment.Builder`.
**Type**
**Checklist**
> Add builder api for EXTRA_SHOW_SUBMIT_BUTTON

- workflow/src/androidTest/java/com/google/android/fhir/workflow/PlanDefinitionProcessorAndroidTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/PlanDefinitionProcessorJavaTest.kt
Ignore blocking unit test in workflow lib to unblock PRs. I opened issue #1890 to track the issue of the failing test
**Checklist**
> Ignore workflow failing test to unblock

- engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt
- engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Fixes #1921
Implemented a new `Search#has` function that accepts resource type as parameter and is not reified. 
The alternative was to update the existing function that is reified and based on generic types. Chose this approach to provide an alternative API for using `Search#has` function instead of refactoring the existing one.
**Type**
**Checklist**
> Implement new Search#has function accepting resource type as param

- datacapture/sampledata/text_questionnaire_decimal.json
- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/EditTextIntegerViewHolderFactory.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/EditTextDecimalViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/EditTextIntegerViewHolderFactoryTest.kt
Fixes #1914
Do not move cursor when leading zero is part of int
No
**Type**
**Checklist**
> Do not move cursor when leading zero is part of int

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
Fixes #1658
I forgot to change this function signature as part of PR #1844
setQuestionnaireResourceContext -> setQuestionnaireLaunchContext 
**Type**
**Checklist**
> update function signature in Fragment that I forgot

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DatePickerViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DateTimePickerViewHolderFactory.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/DatePickerViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/DateTimePickerViewHolderFactoryTest.kt
Fixes #1969 
- Show date pattern text in the lowerCase when get assigned as hint/label for Date and DateTime view. 
- Show date pattern text in the error text in the lowercase when error message get shown.
**Type**
**Checklist**
> Show dateformat text in lowercase for date and dateTime label.

- benchmark/build.gradle.kts
- benchmark/src/androidTest/AndroidManifest.xml
- benchmark/src/androidTest/java/com/google/android/fhir/benchmark/D_FhirJsonParserBenchmark.kt
- benchmark/src/androidTest/java/com/google/android/fhir/benchmark/E_ElmJsonLibraryLoaderBenchmark.kt
- benchmark/src/androidTest/java/com/google/android/fhir/benchmark/H_FhirSyncWorkerBenchmark.kt
- buildSrc/src/main/kotlin/Dependencies.kt
Fixes #1996 
- Added benchmark test for `FHIRSyncWorker` which tests a sample sync pattern for downloading `Patient`s and its related resources (`Observation` and `Encounter`)
- Fixed some broken existing benchmarks
NA
**Type**
Choose one: Testing
5,409,320,711   ns    H_FhirSyncWorkerBenchmark.oneTimeSync_100patients
41,061,074,228   ns    H_FhirSyncWorkerBenchmark.oneTimeSync_1000patients
443,757,834   ns    H_FhirSyncWorkerBenchmark.oneTimeSync_10patients
**Checklist**
> FHIR Sync worker benchmarking

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
Fixes: #1658
Allow multiple resources to be set in context
In the resource table, it says: 
```
Context resources needed for Questionnaire
```
https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-launchContext.html
**Type**
**Checklist**
> Allow multiple resources to be set in context

- demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
- engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
- engine/src/main/java/com/google/android/fhir/sync/Config.kt
- engine/src/main/java/com/google/android/fhir/sync/DataSource.kt
- engine/src/main/java/com/google/android/fhir/sync/DownloadWorkManager.kt
- engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
- engine/src/main/java/com/google/android/fhir/sync/download/DownloaderImpl.kt
- engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpDataSource.kt
- engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpService.kt
- engine/src/main/java/com/google/android/fhir/sync/remote/RetrofitHttpService.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/BundleUploader.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/HttpVerbBasedBundleEntryComponentGenerator.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/HttpVerbBasedBundleEntryComponentImplementations.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt
- engine/src/main/java/com/google/android/fhir/testing/Utilities.kt
- engine/src/test/java/com/google/android/fhir/sync/download/DownloaderImplTest.kt
- engine/src/test/java/com/google/android/fhir/sync/remote/RetrofitHttpServiceTest.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
Fixes #1989 
1. Added a way for users to specify http headers in DownloadWorkManager requests. 
2. Update and Delete requests now use If-Match Http header with [weak Etag](https://hl7.org/fhir/http.html#Http-Headers).
**Type**
**Checklist**
> Support for headers in the http requests.

- workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
Current FhirOperator reloads (and then recompiles) all libraries in every evaluate call, which includes each of the multiple initial expressions in a single questionnaire page. This leads to slow processing of CQL. 
This PR adds a basic **compiled** Library cache that survives multiple executions of the evaluator.
None
**Type**
**Checklist**
> WorkFlow Performance: Adds a compiled Library cache that survives multiple executions of the evaluator.

- engine/src/main/java/com/google/android/fhir/sync/HttpAuthenticator.kt
- engine/src/test/java/com/google/android/fhir/sync/HttpAuthenticatorTest.kt
Fixed Bearer authentication method format issue in HttpAuthenticator.
**Type**
Bug fix 
**Checklist**
> Fixed Bearer authentication method format issue

- demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
- demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
- demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt
- engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
- engine/src/main/java/com/google/android/fhir/sync/Sync.kt
- engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
Give a unique name for the one time sync worker and the periodic worker. Currently, If we have a periodic worker set up, then trigger a oneTime, the periodic worker does not run after as it's over-written due to having the same name. This PR fixes that.
**Type**
**Checklist**
> Give unique name for periodic and oneTime sync worker

- engine/schemas/com.google.android.fhir.db.impl.ResourceDatabase/4.json
- engine/src/androidTest/java/com/google/android/fhir/db/impl/ResourceDatabaseMigrationTest.kt
- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
- engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/DateIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/DateTimeIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/TokenIndexEntity.kt
Fixes #2040
In the Search API, we perform a LEFT JOIN when sorting:
```
LEFT JOIN ${sortTableName.tableName} $tableAlias
ON a.resourceType = $tableAlias.resourceType AND a.resourceUuid = $tableAlias.resourceUuid AND $tableAlias.index_name = ?
```
this join uses the resourceType, resourceUuid and index_name columns. To speed this up, we should create a composite index made up of these 3 columns. We also do the same for the TokenIndexTable
TESTED:
Downloaded 7000 households. Opened App Inspector and ran query generated. Returned results almost instantaneously as opposed to many seconds 
Have …
> Fix Date/DateTime and Token indexes to speed up Search 

- benchmark/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Java.kt
- buildSrc/src/main/kotlin/Plugins.kt
- catalog/build.gradle.kts
- common/build.gradle.kts
- contrib/barcode/build.gradle.kts
- datacapture/build.gradle.kts
- demo/build.gradle.kts
- engine/build.gradle.kts
- knowledge/build.gradle.kts
- testing/build.gradle.kts
- workflow-testing/build.gradle.kts
- workflow/build.gradle.kts
Fixes #2072
We would have to use the beta (Giraffe) or Canary (Hedgehog) version of Android Studio to get 8.1.1 RC to work. Bump down to a version that is stable, which means adding the compileOptions block 
**Type**
**Checklist**
> Dont use AGP RC as that needs a beta version of Android Studio :)

- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponents.kt
Fixes #2071
Append to a mutable list, rather than creating a new list at every recursive call and then adding all its elements to the parent list
**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | **Code health** | Builds | Releases | Other)
**Checklist**
> Optimize flatten and descendent traversal

- buildSrc/src/main/kotlin/Releases.kt
Fixes #2072 
Starting AGP 8.0, automatic component creation is [disabled](https://developer.android.com/build/releases/past-releases/agp-7-1-0-release-notes#disable-component-creation), meaning we need to explicitly configure our publication variant: https://developer.android.com/build/publish-library/configure-pub-variants
Tested:
Ran `./gradlew publishToMavenLocal` and `./gradlew publishReleasePublicationToCIRepository` and they both now work again :) 
Content of command:
**Type**
Choose one: …
> make maven publish work

- buildSrc/src/main/kotlin/Dependencies.kt
- engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
- engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
…onversion fixes
Fixes #881 
**Type**
**Checklist**
> Common lib version update for engine and datacapture with canonical conversion fixes

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
Fixes #2052
There are 2 errors:
1. answerExpressionMap incorrectly caches expressions
2. variables in x-fhir-query are not supported, only launchContext
Solution here is to 
1. refactor to cache only when the full `xFhirExpressionString` has been constructed
2. evaluate variables and their values in fhir-query expression
Removing caching of answer options but that makes it slow.
**Type**
Bug fix | Feature
[Used questionnaire json given in the issue linked]
**Checklist**
> Evaluating variables in answerExpressions

- engine/src/main/java/com/google/android/fhir/testing/Utilities.kt
FhirSyncWorkerTest all pass when they should not due to the JSON payload being empty when uploading localChanges. This is because we are not collecting the flow in upload. Fixed. 
**Type**
**Checklist**
> collect upload to get FhirSyncWorkerTest to work

- engine/src/androidTest/java/com/google/android/fhir/db/impl/ResourceDatabaseMigrationTest.kt
- engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
Fixes #2116
1. Added a default value of EPOCH if migration from string to timestamp fails using [COALESCE](https://www.sqlite.org/draft/lang_corefunc.html#coalesce) .
2. Updated Migration Test to check corrupted timestamp migrates to Instant.EPOCH . 
**Type**
Choose one:  Code health 
**Checklist**
> Added a default value of EPOCH if migration from string to timestamp fails

- engine/src/main/java/com/google/android/fhir/LocalChange.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/BundleEntryComponentGenerator.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/SquashedChangesUploadWorkManagerTest.kt
Fixes #1951, #2031 
*  Introduced a new Type.NO_OP to represent no-operation actions.
*  Modified the mergeLocalChanges function to recognize a local insert followed by a delete, converting the sequence into a Type.NO_OP.
*  Added error handling for unexpected usage of Type.NO_OP within the merge context.
PR #2111
**Type**
**Checklist**
> Handle local insert-delete sequence as no-op when squashing

- demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt
- engine/benchmark/src/androidTest/java/com/google/android/fhir/benchmark/FhirSyncWorkerBenchmark.kt
- engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
- engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
- engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/UploadRequestGenerator.kt
- engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
- engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
We are undergoing a re-degin of the entire upload sync process which will be completed in various steps. To avoid modifying interfaces exposed to the developers in the interim, we are cutting off exposure to the modified interfaces. 
**Type**
feature
**Checklist**
> Not exposing upload work manager to developers

- catalog/src/main/java/com/google/android/fhir/catalog/ComponentListFragment.kt
- catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
- catalog/src/main/java/com/google/android/fhir/catalog/QuestionnaireFileOperationUtil.kt
Fixes #2151 
Miscellaneous components do not have a questionnaire with a validation JSON as compared to other components. As a result, it gives the filename as an empty string from the adapter. This leads to a crash when it attempts to perform a file open operation on an empty string. To prevent this, a non-empty check has been added before performing a file operation on the asset filename
**Type**
Choose one: (Bug fix )
**Checklist**
> Add non empty check on asset file name.

- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreTypes.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreTypesTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/AutoCompleteViewHolderFactoryTest.kt
Fixes #2136 
**Type**
**Checklist**
> Add 'system' in evaluation of unique Coding identifierString

- buildSrc/build.gradle.kts
- catalog/build.gradle.kts
- common/build.gradle.kts
- contrib/barcode/build.gradle.kts
- datacapture/build.gradle.kts
- demo/build.gradle.kts
- engine/benchmark/build.gradle.kts
- engine/build.gradle.kts
- knowledge/build.gradle.kts
- workflow-testing/build.gradle.kts
- workflow/benchmark/build.gradle.kts
- workflow/build.gradle.kts
Update gradle build tool from 8.0.2 t0 8.1.1
NA
**Type**
Builds
**Checklist**
> Update gradle build tool from 8.0.2 to 8.1.1

- .github/workflows/build.yml
This increases the size of the VM [used for CI](https://github.com/google/android-fhir/actions/workflows/build.yml) jobs runs from [GitHub's default](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) from / to:
* 2-core => 64-cores CPU
* 7 GB => 256 GB RAM
* 14 GB => 2040 GB of SSD space
This should fix the `Error: The operation was canceled` problem described in issue #2197.
This is a worthwhile trade off of expensive engineering time VS infrastructure cost. Thank You Sundar for paying for this to enable this project to productively produce an Open Health Stack!
_Have you considered any alternatives? And if so, why have you chosen the approach in …
> Very significantly increase CI VM CPU Cores, RAM & disk (re. #2197)

- buildSrc/src/main/kotlin/Dependencies.kt
Note how the same copyright header is present twice im this file.
> clean: Remove double copyright header

- buildSrc/build.gradle.kts
This was automatically proposed when I opened this project in Android Studio today.
> Bump com.android.tools.build:gradle from 8.1.1 to 8.1.2

- engine/schemas/com.google.android.fhir.db.impl.ResourceDatabase/7.json
- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- engine/src/androidTest/java/com/google/android/fhir/db/impl/ResourceDatabaseMigrationTest.kt
- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
- engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/LocalChangeEntity.kt
- engine/src/test/java/com/google/android/fhir/LocalChangeTest.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/UploaderImplTest.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGeneratorTest.kt
Fixes #2209 
- We need to LocalChangeEntity agnostic of the resource ID as there can be cases where the resource ID of a resource might change (POST for creation). In such cases we can use resource UUID to keep the mapping between the resource and LocalChanges intact.
- Fixing the `ResourceDatabaseMigrationTest` to use the migrated database for the particular implemented migration to run assertions
- There are cases where in download of a resource which already exists in the database leads to new resource UUID being assigned to the same resource. Hence we need to keep the same resource UUID as the previous version in such cases
One …
> Add resource UUID to LocalChangeEntity, fixing changing UUID issue for the same resource 

- docs/index.html
Related to #2232
This is just a very small start which will (should) make https://google.github.io/android-fhir/ not be a 404.
I have ideas for (much) more to come here, later.
> Add initial docs/index.html (re. #2232)

- buildSrc/src/main/kotlin/LicenseeConfig.kt
- common/build.gradle.kts
Starts to Fix #2172 
This is the first step to migrate the engine and then the workflow to a new version
**Type**
Feature
**Checklist**
> Moves commons to HAPI 6.8, removes caffeine and forces guava-android

- .github/dependabot.yaml
This should fix the latest new problem on #2195.
> Fix broken dependabot.yaml syntax again (re. #2195)

- engine/benchmark/src/androidTest/java/com/google/android/fhir/benchmark/FhirSyncWorkerBenchmark.kt
> SdkSuppress FhirSyncWorkerBenchmark oneTimeSync_50patients (re. #2235)

- knowledge/src/androidTest/java/com/google/android/fhir/knowledge/db/impl/KnowledgeDatabaseTest.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/LocalFhirNpmPackageMetadata.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/db/DbTypeConverters.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/db/KnowledgeDatabase.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/db/dao/KnowledgeDao.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/db/entities/ImplementationGuideEntity.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/db/entities/ImplementationGuideResourceMetadataEntity.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/db/entities/ResourceMetadataEntity.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/files/NpmFileManager.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/npm/NpmPackageDownloader.kt
- knowledge/src/main/java/com/google/android/fhir/knowledge/npm/OkHttpNpmPackageDownloader.kt
- knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerNpmTest.kt
- knowledge/src/test/java/com/google/android/fhir/knowledge/KnowledgeManagerTest.kt
- knowledge/src/test/java/com/google/android/fhir/knowledge/files/NpmFileManagerTest.kt
- knowledge/src/test/java/com/google/android/fhir/knowledge/npm/OkHttpNpmPackageDownloaderTest.kt
- workflow/benchmark/src/androidTest/java/com/google/android/fhir/workflow/benchmark/F_CqlEvaluatorBenchmark.kt
- workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/FhirEngineDalTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/FhirEngineRetrieveProviderTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/FhirEngineTerminologyProviderTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateJavaTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
- Allow custom package option in the `create` API of Knowledge Manager
- Simplify the `create` APIs for Knowledge Manager by merging two versions into one
- Refactor KnowledgeManager to be a class that coordinates between 1) db indices 2) local files and 3) downloader
- Organise package structure to reflect the three components: `db`, `files`, `npm`
- Remove dependency from downloader to file manager to make responsibilities clear
NA
**Type**
Feature
**Checklist**
> Allow custom package server in Knowledge Manager

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/FirebaseTestLabConfig.kt
- buildSrc/src/main/kotlin/LicenseeConfig.kt
- catalog/build.gradle.kts
- contrib/barcode/build.gradle.kts
- datacapture/build.gradle.kts
- datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/FHIRPathEngineHostServices.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/FHIRPathEngineHostServicesTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
- demo/build.gradle.kts
- engine/benchmark/build.gradle.kts
- engine/build.gradle.kts
- engine/src/main/java/com/google/android/fhir/index/DualHapiWorkerContext.kt
- engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
- engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
- knowledge/build.gradle.kts
- settings.gradle.kts
- workflow-testing/build.gradle.kts
- workflow/benchmark/build.gradle.kts
- workflow/build.gradle.kts
Migrates engine to HAPI 6.8 while forcing Workflow to stay on 6.0
**Type**
Feature 
**Checklist**
> Migrates engine to HAPI 6.8 while forcing Workflow to stay on 6.0

- workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
- workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
The idea is to: 
1. clarify the need to send a full reference "type/id" instead of just the ID
2. clarify that any reference (e.g. Patient, Group) would work, not only Patient. 
3. match the evaluator's name
**Checklist**
> Renames generateCarePlan's param from patientId to subject

- codelabs/datacapture/app/build.gradle.kts
- codelabs/datacapture/build.gradle.kts
- codelabs/datacapture/gradle/wrapper/gradle-wrapper.properties
- codelabs/engine/app/build.gradle.kts
- codelabs/engine/app/src/main/java/com/google/android/fhir/codelabs/engine/PatientItemRecyclerViewAdapter.kt
- codelabs/engine/app/src/main/java/com/google/android/fhir/codelabs/engine/PatientItemViewHolder.kt
- codelabs/engine/app/src/main/java/com/google/android/fhir/codelabs/engine/PatientListViewModel.kt
- codelabs/engine/build.gradle.kts
- codelabs/engine/gradle/wrapper/gradle-wrapper.properties
* Update colab to use latest engine lib
* Update other dependencies to latest, even gradle
**Type**
**Checklist**
> Update dependencies in engine colab

- engine/src/main/java/com/google/android/fhir/MoreResources.kt
- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
- engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
Fixes #2271
When updates are downloaded from the server, the database update code wasn't putting the new versionID of the updated resource into the table. 
**Type**
**Checklist**
> Update the version of resource after updates are downloaded from the server

- buildSrc/src/main/kotlin/Dependencies.kt
- datacapture/build.gradle.kts
- workflow/build.gradle.kts
Use published libraries in workflow library's dependencies
Current approach is not publishable.
**Type**
Builds
**Checklist**
> Use published libraries in workflow library's dependencies

- settings.gradle.kts
This is better than #2283 and #2285.
> Bump Jackson versions in (only) buildscript from 2.15.2 to 2.15.3

- buildSrc/src/main/kotlin/Dependencies.kt
- datacapture/build.gradle.kts
- gradle/libs.versions.toml
see #2302 
My expectation is that if this passes CI and gets merged, Dependabot will automagically propose a bump for Glide - let's try and see.
If this works, we should then migrate to this model. Perhaps that's something that could be "crowd sourced" and fanned out, instead of me doing all migrations myself?
PS: There would be an intermediate phase with "mixed" dependency declaration; to me such a "gradual adoption" is a "feature not a bug", with testing each change, and more sensible than a single big bang all in one migration.
> Introduce Version Catalog, initially intentionally only for Glide

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
see #1482 for background:
[Here](https://firebase.corp.google.com/project/android-fhir-instrumeted-tests/testlab/histories/bh.96901a7d2453dacf/matrices/5229748969591520332/executions/bs.24456ec5fee68df1/testcases/4/errors) for #2316 that `selectOther_shouldScrollDownToShowAddAnotherAnswer()` in the `QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest` now failed even on API Level 33, not just 24, so let's entirely `@Ignore` it, until someone digs more deeper into how to fix this properly, to avoid friction?
```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131230791/com.google.android.fhir.datacapture.test:id/add_another>
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1024, height=2209, has-focus=true, …
```
> Ignore known flaky test on all API Levels (re. #1482)

- codelabs/datacapture/gradle.properties
- codelabs/engine/README.md
- codelabs/engine/app/build.gradle.kts
- codelabs/engine/gradle.properties
Get engine codelab to work with the latest version of the engine lib
The main change is to disable Android Jetifier when building the app. The Jackson library is not compaitble with Jetifier.
**Type**
**Checklist**
> disable jetifier in codelab and bump to use latest version of engine

- .github/workflows/runFlank.sh
- kokoro/gcp_ubuntu/kokoro_build.sh
Related to #2304
This factors out the `runFlank` stuff from `kokoro_build.sh` into a separate new `runFlank.sh` script.
The idea here is that I'll then invoke this `runFlank.sh` from the GitHub Action in #2321.
> Factor out runFlank (re. #2321)

- .github/workflows/build.yml
- .github/workflows/codeql.yaml
See https://github.com/styfle/cancel-workflow-action/blob/main/README.md (and go/github-actions#cancel-workflows)
I've intentionally raised this separately from #2313 (which is included here) and #2314 (which builds on this) to make it easier to review, and revert in case it's needed because this unexpectedly breaks anything (which it should not).
This should be rebased after #2313 is merged.
> Replace styfle/cancel-workflow-action with new GitHub `concurrency:` standard

- engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
- engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Fixes #2331
Search query generated because of the [has](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt#L42C42-L42C45) block was resulting in a full table scan instead of using an index.
The new query now is able to use this [composite index](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt#L30) of `resourceType` and `resourceId`.
**Type**
**Tested Search request** 
``` …
```
> Updated the nested query to be able to use the index for searching instead of a full table scan

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/QuestionnaireUiEspressoTest.kt
Adding constraint to run on a minimum Android SDK version of 33.
**Type**
**Checklist**
> clearAllAnswers_shouldClearDraftAnswer : update min sdk version 33

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DatePickerViewHolderFactory.kt
Fixes #2354 
Initiate the TextWatcher after calling `textInputEditText.removeTextChangedListener(textWatcher)`
N/A
**Type**
Bug fix
[Screen_recording_20231210_222606.webm](https://github.com/google/android-fhir/assets/62053304/abe80a4e-1429-42d1-ab7a-bfe4ed63df24)
**Checklist**
> Fix TextWatcher initialization in date picker widget

- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/EditTextDecimalViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/EditTextIntegerViewHolderFactory.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/EditTextDecimalViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/EditTextIntegerViewHolderFactoryTest.kt
Fixes #2401
Updated the code to
1. Set the draft answer correctly.
2. Clear the answers when possible rebind occurs ( no draft or answer is available to be set).
**Type**
**Checklist**
> Cleanup the text during the re-bind of the Decimal and Integer view holders.

- workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
- workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
The methods [fhirOperator.evaluateLibrary](https://github.com/google/android-fhir/blob/master/workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt#L85) do not allow passing null in expression which results in forcing user to output specific variables only. The evaluator  in cql allows passing null and when its null whole library  processing result is output. We have cases when we want the whole evaluation accessible.
See details in org.opencds.cqf.cql.engine.execution.CqlEngine#evaluate
**Type**
**Checklist**
> Allow nullable expressions in library evaluator

- engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
As per the [Fhir http rules](https://hl7.org/fhir/R4/http.html#trules), a Bundle transaction with multiple operations on the same resource can be rejected by the FHIR server. So removing the UploadStrategy.AllChangesBundlePut option as it may result in a Bundle with multiple updates on a same resource .
**Type**
**Checklist**
> Remove UploadStrategy.AllChangesBundlePut option from engine.

- .github/workflows/build.yml
- .github/workflows/codeql.yaml
Related to #2232
This is a mechanical reformat of the x2 YAML in `.github/workflows`.
It was done by https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions.
This makes future changes easier to review.
**Type**
**Checklist**
> Mechanical reformat of .github/workflows

- .github/workflows/build.yml
- .github/workflows/codeql.yaml
- .gitignore
- build-docs.bash
Related to #2232
This PR contains x2 Commit. You may want to review and merge #2459 separately, first? Or both together here - your call.
I'm intentionally raising small changes; this alone doesn't "do" all that much, yet; my plan is to gradually build upon this.
**Type**
**Checklist**
> Introduce script and action step to build documentation

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/OptionSelectDialogFragment.kt
Fixes #2436
Add `optionExclusive` extension support for `answerOption` in Popup for more than 10 items.
**Type**
Choose one: (Bug fix | Feature)
**Checklist**
> Added Support for optionExclusive Extension in Popup

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
- datacapture/src/main/res/layout/questionnaire_fragment.xml
- datacapture/src/main/res/values/dimens.xml
- datacapture/src/main/res/values/styles.xml
Fixes #2446 
If there is no button visible in the bottom navigation container then it was overlapping review mode recyclerview, as result screen was appearing blank.
Now issue is fixed by hiding bottomNavigation container if there is no children.
**Type**
**Checklist**
> Hide the bottom navigation container if there are no visible buttons.

- build-docs.bash
- docs/index.html
Part of #2232.
Enabled by #2463, this generates the Kotlin API docs on https://google.github.io/android-fhir/ during the CI build. (They were "static" before, and just deployed from what was in the `docs/` directory, with this, they are "built". This is the 1st step towards generating more documentation during the build in a future next step.)
Originally raised as #2483, but that PR for some strange reason didn't update even though I (force) pushed new commit.
@williamito or @santosh-pingle or @MJ1998 or @jingtang10  OK for you?
~Includes #2463, but just for testing; when this works, I'll merge that, and then rebase this to not include that anymore.~
~I'm marking this one as draft as I'm still testing this - please do not merge as long as it's in Draft.~
> Generate API docs site during build

- engine/src/androidTest/java/com/google/android/fhir/db/impl/dao/LocalChangeDaoTest.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
Fixes #2495 
Issue: 
As pointed by @LZRS in the #2495 description ,
The sql query  in the `LocalChangeDao.getReferencesForLocalChanges `should use `IN` operator instead of `=` operator to fetch all LocalChangeResourceReferenceEntity for the passed LocalChange ids.
Changes:
1. Updated sql query to use `IN`.
2. Added test to check the usage of `LocalChangeDao.getReferencesForLocalChanges ` with single and multiple LocalChange .
**Type**
**Checklist**
> Fixed the db query to get LocalChangeResourceReferenceEntity.

- datacapture/src/main/java/com/google/android/fhir/datacapture/expressions/EnabledAnswerOptionsEvaluator.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
This is a trivial change. Source: [Comment link](https://github.com/google/android-fhir/pull/2478#pullrequestreview-1949097727)
**Type**
Code health
**Checklist**
> Rename extractDependentVariables to extractItemDependentVariables

- .devcontainer/devcontainer.json
- .github/dependabot.yaml
- .vscode/extensions.json
- docs/contrib/codespaces.md
see #2481
@jingtang10 & @santosh-pingle how about this?
> Initial GitHub Codespaces (AKA Dev Container) configuration (see #2481)

- datacapture/src/main/res/layout/questionnaire_fragment.xml
Fixes #2516 
Issue was constraints applied to the buttons.
Initial Constraints :
[Prev] -> [Next] -> [Submit] [Review]
So if submit and next button becomes invisible, prev was hiding below review
Current Constraints :
[Prev] -> [Next] -> [Review] -> [Submit]
**Type**
**Checklist**
> Fixed Hidden Previous Button in Review Mode

- .gitignore
- build-docs.bash
- datacapture/build.gradle.kts
- docs/use/api.md
- engine/build.gradle.kts
- knowledge/build.gradle.kts
- mkdocs.yaml
- workflow/build.gradle.kts
Follow-up to #2513 for #2232
This will fix the currently broken links on https://google.github.io/android-fhir/use/api/.
It also automagically makes sure that they will never break again in the future by enabling link validation.
@MJ1998 LGTY?
@fredhersch FYI
> Fix broken Dokka API Doc links on brand new website

- mkdocs.yaml
A simple 'full' menu on the left seems much clearer, actually.
This just changes the "look and feel" (content remains the same).
It also removes one entry which was a duplicate.
Follow-up to #2513 for #2232.
@MJ1998 LGTY?
> Disable top-level navigation tabs on new website

- CODEOWNERS
This initial list matches https://github.com/orgs/google/teams/android-fhir-reviewers.
We were not able to get @google/android-fhir-reviewers working; see https://github.com/google/android-fhir/pull/2536 for background, this PR is an alternative to that one.
See https://github.com/google/android-fhir/issues/2320 for overall motivation.
Fixes #2320.
> Update CODEOWNERS to assign listed individuals instead of group as reviewers of PRs

- engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
- engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Fixes #2547 
As [commented](https://github.com/google/android-fhir/issues/2547#issuecomment-2123426078) in the above issue, this change reduces time from ~25 seconds to few milliseconds (7k patients).
Remove extra JOIN clause (`a.resourceType = b.resourceType`). This clause is not needed as we already filter the resourceType in WHERE clause. 
Sample DSL search:-
```
fhirEngine.search<Patient> {
sort(Patient.NAME, Order.ASCENDING)
count = PaginationConstant.DEFAULT_PAGE_SIZE
from = currentPage * PaginationConstant.DEFAULT_PAGE_SIZE
}
```
Query before this change:-
```
SELECT a.resourceUuid, a.serializedResource
FROM ResourceEntity a
LEFT JOIN StringIndexEntity b
ON …
```
> Improve search speed 

- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
Fixes #2552 
Removes wrapping of db transaction for single resources reads to prevent potential blocking
**Type**
**Checklist**
> Remove wrapping transaction for single read api

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
The current logic to pack repeated groups does not actually look at the questionnaire item at all. It simply packs multiple groups of the same id and assume they are from the same repeated group. This is fine unless if there is only one repeated group answer, the logic won't be able to distinguish this from non-repeated group.
The fix adds the questionnaire item to the logic so it packs if and only if it's a repeated group.
**Type**
Bug fix
**Checklist**
> Pack repeated groups even if there is only one group in the response

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
Fixes #726 
In paginated layout, empty repeated group header was shown.
issue : 
It was creating empty answer component for repeated group item while packing repeated group header.
fix : 
1. do not create empty response item component for repeated group header. 
2. do not filter empty answer component for repeated group  
**Type**
**Checklist**
> Handle empty repeated group header.

- datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItemTest.kt
Fixes # 
Link the test `answers should reflect initial response item components` present in the QuestionnaireViewItemTest to issue #2593.
**Type**
Choose one: (Code health)
**Checklist**
> Link the test to issue 2593.

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponents.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/GroupViewHolderFactory.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponseItemComponentsTest.kt
Fixes #2590
At the moment we are copying nested items to answers with nested items. This would wipe out any existing answers to nested questions.
This PR makes sure we only copy nested items to new answers. It also improves documentation significantly and adds tests.
**Type**
Bug fix
**Checklist**
> Only copy nested items to childless answers

- demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
- engine/src/main/java/com/google/android/fhir/sync/Sync.kt
- engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
Fixes #
Added Blocked state to the CurrentSyncJobStatus.
**Type**
**Checklist**
> Blocked state to CurrentSyncJobstatus.

- README.md
- docs/community.md
- docs/index.md
- mkdocs.yaml
- Move the duplicated content from the README.md file to the doc site
- Add community page in the doc site to centralize all community information
- Move roadmap page to the top level navigation (it was nested under contributors)
NA
**Type**
Documentation
**Checklist**
> Move `README.md` content to the doc site

- docs/contrib/docs.md
- docs/contrib/git.md
- docs/git.md
- mkdocs.yaml
@jingtang10 the other day in the meeting you suggested "sharing git know how" - here's a start, is this useful?
@omarismail94 and @fredhersch FYI
> Initial Git Tips documentation for contributors

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/LicenseeConfig.kt
- gradle/libs.versions.toml
- workflow-testing/build.gradle.kts
- workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilder.kt
- workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/IGInputStreamStructureRepository.kt
- workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/PlanDefinition.kt
- workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/TestRepositoryFactory.java
- workflow-testing/src/main/resources/plan-definition/anc-visit/anc_visit_careplan.json
- workflow-testing/src/main/resources/plan-definition/base-repo/tests/CarePlan-generate-questionnaire.json
- workflow-testing/src/main/resources/plan-definition/base-repo/tests/CarePlan-hello-world-patient-view.json
- workflow-testing/src/main/resources/plan-definition/base-repo/tests/CarePlan-prepopulate.json
- workflow-testing/src/main/resources/plan-definition/cds-hooks-multiple-actions/cds_hooks_multiple_actions_careplan.json
- workflow-testing/src/main/resources/plan-definition/cql-applicability-condition/care_plan.json
- workflow-testing/src/main/resources/plan-definition/med-request/med_request_careplan.json
- workflow/benchmark/build.gradle.kts
- workflow/build.gradle.kts
- workflow/sampledata/smart-imm/tests/IMMZ-Patient-NoVaxeninfant-f/CarePlan/CarePlan.json
- workflow/src/androidTest/java/com/google/android/fhir/workflow/CqlBuilderAndroidTest.kt
- workflow/src/androidTest/java/com/google/android/fhir/workflow/PlanDefinitionProcessorAndroidTest.kt
- workflow/src/androidTest/java/com/google/android/fhir/workflow/SmartImmunizationAndroidTest.kt
- workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
- workflow/src/test/java/com/google/android/fhir/workflow/CqlBuilderJavaTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
- workflow/src/test/java/com/google/android/fhir/workflow/PlanDefinitionProcessorJavaTest.kt
Update clinical reasoning dependencies to `3.8.0`
Include `logback-android` dependency and exclude `logback-classic` for build to work on Android.
Ignore tests that are currently failing. Follow up in https://github.com/google/android-fhir/issues/2638
NA
**Type**
Builds
**Checklist**
> Update clinical reasoning dependencies

- .devcontainer/devcontainer.json
Fixes #2614
This fixes #2614.
It works around https://github.com/akhildevelops/devcontainer-features/issues/9.
Wait for https://github.com/akhildevelops/devcontainer-features/issues/9 and then bump 0.0.2 to 0.0.3.
But no need, this works great - I've tested it.
**Type**
Choose one: **Bug fix** ~~Feature | Documentation | Testing | Code health | Builds | Releases | Other~~
> Fix Codespace with chown /opt/android workaround (fixes #2614)

- CODEOWNERS
The "Enable auto assignment" option in teams were enabled, giving it another try 
**Type**
Choose one:  Other
**Checklist**
> Update CODEOWNERS to use group instead of individuals

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Fixes #2655
If you have a questionnaire item inside a repeated group, but the related response item is missing, then you call `addMissingResponseItems`. The missing response item is still missing.
An exception will show if you try to call `forEachItemPair` function where you need to have the exact same size between questionnaire items and response items.
This PR fixes that.
N/A
**Type**
Bug fix
**Checklist**
> Add missing response items to repeated group child items

- contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/BarCodeReaderViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/ReviewViewHolderFactory.kt
Fixes #2664
Add missing use of viewItem.questionText
N/A
**Type**
Bug fix
**Checklist**
> Add missing use of viewItem.questionText

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
Fixes #2444 
Add bundle argument `EXTRA_SHOW_SUBMIT_ANYWAY_BUTTON` in `QuestionnaireFragment.kt` and `QuestionnaireValidationErrorMessageDialogFragment.kt` to optionally disable submit anyway if it's not needed. Default value for the same is `true`. 
Defines a setter in `QuestionnaireFragment.kt` so that it's value can be easily set while creating an instance of QuestionnaireFragment. Add Relevant test methods for the same
N/A
**Type**
Bug fix
N/A
**Checklist**
> Add argument to disable Submit anyway button in the questionnaire confirmation popup

- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- engine/src/main/java/com/google/android/fhir/FhirEngine.kt
- engine/src/main/java/com/google/android/fhir/db/Database.kt
- engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
- engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/Uploader.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerChangePatchGenerator.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
- engine/src/main/java/com/google/android/fhir/testing/Utilities.kt
- engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
- engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/UploaderTest.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGeneratorTest.kt
To ensure all database operations originate from the `FhirEngineImpl` class, the synchronization functions should be refactored.  Instead of directly accessing the database within the PatchGenerator class, the lambda functions used in the synchronization process should be modified to accept a `List<LocalChangeResourceReference>` object as input. This list will contain references to the resources that require synchronization, allowing FhirEngineImpl to handle the necessary database interactions.
This approach centralizes database access in `FhirEngineImpl`, improving code organization and maintainability.
Clear and concise code change …
> Decoupling Database Access in FHIR Patch Generation

- demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt
- engine/benchmark/src/androidTest/java/com/google/android/fhir/benchmark/FhirSyncWorkerBenchmark.kt
- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
- engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
- engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
- engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt
- engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
- engine/src/test/java/com/google/android/fhir/sync/upload/ResourceConsolidatorFactoryTest.kt
Partially Fixes #2686 
This improves configuration format and adds option to upload "updates to a resource" using PUT http method.
**Type**
Choose one: Feature | Code health
**Checklist**
> Configuration changes to accept UploadStrategy

- engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
- engine/src/main/java/com/google/android/fhir/sync/Sync.kt
…the periodic sync.
Update enqueued state as current state after iteration completion in the periodic sync.
**Type**
**Checklist**
> Update enqueued state as current state after iteration completion in the periodic sync.

- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreTypes.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/OptionSelectDialogFragment.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/AutoCompleteViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/CheckBoxGroupViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/RadioGroupViewHolderFactory.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/ReviewViewHolderFactory.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/CheckBoxGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/RadioGroupViewHolderFactoryTest.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/ReviewViewHolderFactoryTest.kt
Fixes #2688
Apply to spanned for answer options
N/A
**Type**
Feature
**Checklist**
> Apply toSpanned for answer options

- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
Fixes #1899
Pack repeated groups recursively
NA
**Type**
Bug fix
**Checklist**
> Pack repeated groups recursively

- catalog/src/main/assets/component_modal.json
- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapterTest.kt
- docs/use/extensions.md
Fixes #2662
- Define dialog extension https://github.com/google/android-fhir/dialog
- Use dialog: if the item control is checkbox or radio button, and has dialog extension
FHIR Chat discussion about adding `dialog` control type to Jira:
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/dialog.20item.20control
N/A
**Type**
Feature
**Checklist**
> Add dialog extension

- buildSrc/src/main/kotlin/Releases.kt
- docs/use/api.md
Bump the engine version to 1.1.0
NA
**Type**
Releases
**Checklist**
> Bump the engine version to 1.1.0

- engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
- engine/src/androidTest/java/com/google/android/fhir/db/impl/EncryptedDatabaseErrorTest.kt
- engine/src/androidTest/java/com/google/android/fhir/db/impl/dao/LocalChangeDaoTest.kt
- engine/src/main/java/com/google/android/fhir/FhirServices.kt
- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
- engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
- engine/src/main/java/com/google/android/fhir/sync/upload/request/UrlRequestGenerator.kt
- engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
- gradle/libs.versions.toml
- knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
Fixes #2748
**Type**
**Checklist**
> Refactor usages of Json Parser for thread safety

- docs/use/SDCL/Author-questionnaires.md
Update version number to `2.2` instead of `2.1.1` in documentation under `Questionnaire basics` section as according to the JSON snippet provided, item `2.2` is only shown if item `2.1` is `true`
**Type**
Documentation
N/A
**Checklist**
> Fix version number under Questionnaire basics section

- datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
Instead of just as group
Fixes #2752 
**Type**
**Checklist**
> Validate QuestionnaireItem.Group with repeats as repeating group

- engine/schemas/com.google.android.fhir.db.impl.ResourceDatabase/10.json
- engine/src/androidTest/java/com/google/android/fhir/db/impl/ResourceDatabaseMigrationTest.kt
- engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
- engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/DateIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/DateTimeIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/NumberIndexEntity.kt
- engine/src/main/java/com/google/android/fhir/db/impl/entities/StringIndexEntity.kt
Improves performance for queries that may involve sorting with search params
Fixes https://github.com/google/android-fhir/issues/2758
**Type**
**Checklist**
> Include index_name column in index for tables used in sorting

- datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/DropDownViewHolderFactoryEspressoTest.kt
- datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
- datacapture/src/main/res/drawable/ic_clear.xml
- datacapture/src/main/res/layout/drop_down_view.xml
- datacapture/src/main/res/values/dimens.xml
- datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactoryTest.kt
Fixes #2228
- Use `questionnaireViewItem.answers` state to check if the AutoComplete is editable or not
- Remove keyListener to make the AutoComplete not editable
- Hide keyboard after typing an option then clicking the shown option
- Show clear icon when answer is selected
N/A
**Type**
Bug fix
[dropdown-behavior-demo-2.webm](https://github.com/user-attachments/assets/78b862d4-9e73-458d-b1bf-688ebe82fb23)
**Checklist**
> Disable typing when dropdown has answer

- datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
- datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
Fixes #2797
Use toSpanned in validation error dialog text
Another way is to remove the HTML, to only extract the text content.
But, just using toSpanned is much simpler.
**Type**
Bug fix
**Checklist**
> Use toSpanned in validation error dialog text

- .github/workflows/build.yml
This is a http://go/LSC run by http://go/ghss to upgrade all self-hosted ubuntu-22.04 runners to ubuntu-24.04.
This is a courtesy PR to help you upgrade to the latest release of ubuntu runners, it is not mandatory at this time.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it.
More context and feedback: http://b/406537467
> Upgrade all self-hosted ubuntu-22.04 runners to ubuntu-24.04.
