datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryInstrumentedTest.kt, datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactoryInstrumentedTest.kt, datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
=> SDC fixed Instrumented Android unit tests

datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt, datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt, datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireResponseDialogFragment.kt
=> Handling crash due to configuration change / application minimization by using Saved State module for ViewModel

example/src/main/java/com/google/fhirengine/example/FhirApplication.kt, example/src/main/java/com/google/fhirengine/example/PatientListActivity.kt, example/src/main/res/menu/list_options_menu.xml, example/src/main/res/values/strings.xml, fhirengine/src/main/java/com/google/fhirengine/sync/ResourceSynchronizer.kt
- Fix `java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: YearOfEra` exception.
- Change initial patient sync paramters to address-city=NAIROBI
- Pass a new instance of patient list to refresh RecyclerView
- Remove "About Fire Engine" menu entry.
Fixes #110 and #128
=> Fix DateTimeFormatter and Min API Level issues.

fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt, fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/ResourceDao.kt, fhirengine/src/test-common/java/com/google/fhirengine/resource/TestingUtils.kt, fhirengine/src/test/java/com/google/fhirengine/impl/FhirEngineImplTest.kt
* Change from delete and reinsert to updating the rows via query
* Change non-existent resource update test to expect no insertion
=> Use SQL update rather than delete and insert for updating resources

datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryInstrumentedTest.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderTypeTest.kt
=> SDC questionnaire integer edit text widget

datacapturegallery/src/main/assets/patient-registration.json
=> Change the max length extension values from string to integer

datacapturegallery/src/main/assets/patient-registration.json
=> Update the patient registration example to use the maxLength field correctly

datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextDecimalViewHolderFactoryInstrumentedTest.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextDecimalViewHolderFactory.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderTypeTest.kt
=> Add support for DECIMAL type questions using EditText widget

datacapturegallery/src/main/assets/openhie-covid-case-report.json, datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
=> Add COVID-19 case report questionnaire to the sdc gallery

datacapturegallery/src/main/assets/iprd-hiv-fhir-questionnaire.json, datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
#203 The questionnaire was converted to FHIR format using the [LHC form builder tool](https://lhcformbuilder.nlm.nih.gov/)
=> Added HIV risk assessment questionnaire developed by IPRD and WITS

datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactoryInstrumentedTest.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt, datacapture/src/main/res/layout/questionnaire_item_display_view.xml
=> Create widget to render questionnaire item of type display

datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryInstrumentedTest.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
=> Fix the radio button bug in the sdc gallery

fhirengine/build.gradle
Set `coreLibraryDesugaringEnabled true` in `fhirengine.gradle` `compileOptions`
=> Enable core lib desugaring on fhirengine

datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderTypeTest.kt
=> Bug fix add display type to adapter and view holder type

datacapture/build.gradle, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextDecimalViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextMultiLineViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextStringViewHolderDelegate.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt
This will be used to generate the artifacts to be published on maven.
Closes #195
=> Create a new publishing task in gradle

datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensions.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt, datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml, datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensionsTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
Just a low hanging fruit ;) . Added radio-button to the supported list of item-control extensions and fixed the OutlinedBox issue for drop down mentioned in #228
=> Add radio button to item control

README.md
Updated read me in advance of SDC library release note
=> Add project details to the README file

datacapture/src/main/res/drawable/gm_schedule_24.xml, datacapture/src/main/res/layout/questionnaire_item_slider.xml
ran `addlicense -c "Google LLC" -l apache .`
=> Add License

datacapture/src/main/res/layout/questionnaire_item_radio_group_view.xml
=> extra namespace removed

datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
=> capitalized replaced

datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt, datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt, datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
**Fixes**: 
Prefilled questionnaire example was removed in a previous commit. Adding it back.
**Type**
Bug fix
=> Add prefill example back to the application

.github/PULL_REQUEST_TEMPLATE.md
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**
Fixes #[issue number] (Issue not created as it seemed too trivial to gain its position in issue board)
The word `Fixes` in bold format does not link the issue, so that specific word should be plain text only to get the issue link working
None
**Type**
(Other)
NA
**Checklist**
=> Remove markdown from `Fixes`

core/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt, core/src/main/java/com/google/android/fhir/FhirEngine.kt, core/src/main/java/com/google/android/fhir/db/Database.kt, core/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt, core/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt, core/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**
Fixes #404 
Use Kotlin `vararg` to combine solo and batch APIs in `FhirEngine` and `Database`.
NA
**Type**
Code health
**Checklist**
=> Use Kotlin `vararg` to combine solo and batch APIs in `FhirEngine` and `Database`

core/src/main/java/com/google/android/fhir/search/MoreSearch.kt, core/src/test/java/com/google/android/fhir/search/SearchTest.kt
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**
Fixes #400 
added case insensitivity
N/A
**Type**
Choose one:  Feature
**Checklist**
=> case-insensitive search

datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
**Fixes**: 
#425 
**Description:**
Line number 103 has to be changed in file QuestionnaireItemDateTimePickerViewHolderFactory.kt
**Type**
=> Update QuestionnaireItemDateTimePickerViewHolderFactory.kt for fixing #425

core/src/main/java/com/google/android/fhir/db/Database.kt, core/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
Remove unused APIs in database. These search APIs will be replaced by `search`.
N/A
**Type**
Code health
**Checklist**
=> Remove unused APIs in the database interface

README.md
Fixes N/A
Add a release badge in the README.md file for the FHIR engine lib. 
N/A
**Type**
Documentation
N/A
**Checklist**
=> Add the release badge for FHIR Engine library

.github/workflows/ci.yml
trivial
Skip the workflow if changes are made only to .md files ( like `readme.md`) 
We could add the `license.txt` file as well but spotless check might fail if changes are made to the file so I've decided to include it. 
**Type**
Choose one: (Other)
**Checklist**
=> chore : Add relevant files to `paths-ignore`

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Plugins.kt, datacapture/build.gradle.kts, engine/build.gradle.kts
Fixes: NA
Update android gradle plugin to 4.2.1
NA
**Type**
Choose one: Build
NA
**Checklist**
=> Update android gradle plugin to 4.2.1

engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
Fixes [#485](https://github.com/google/android-fhir/issues/485)
Changed the use of `@Transaction` annotation to `db.withTransaction {}`
N.A
**Type**
**Checklist**
=> Update db transaction annotation to real transaction

buildSrc/src/main/kotlin/Dependencies.kt
Fixes #473
Update room version to 2.3.0 
**Type**
**Checklist**
=> Upgraded Room from version 2.2.5 to 2.3.0

README.md, docs/contributing.md
NA
Move code snippets from README.md to the wiki. Add developers guide to contributing.md.
NA
**Type**
Documentation
**Checklist**
=> Move code snippets from README.md to the wiki. Add developers guide to contributing.md.

datacapturegallery/src/main/res/layout/questionnaire_list_item_view.xml
#561
Three dots for longer questionnaire title.
N/A
**Type**
Improvement
**Checklist**
=> ellipsize attribute added

buildSrc/src/main/kotlin/Dependencies.kt
Fixes #539 
* Robolectric version bumped to 4.5.1
Simplest fix.
**Type**
Choose one: Other (dependency version bump)
**Checklist**
=> Robolectric version bump

CODEOWNERS
Fixes NA
Add @stevenckngaa as a code owner
NA
**Type**
Choose one: Other
**Checklist**
=> Add @stevenckngaa as a code owner

engine/src/main/java/com/google/android/fhir/db/Database.kt, engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt, engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
=> Use suspend functions in the databasae

datacapture/build.gradle.kts
Bump up version of data capture library to 0.1.0-alpha03
NA
**Type**
Releases
**Checklist**
=> Bump up version of data capture library to 0.1.0-alpha03

buildSrc/src/main/kotlin/Plugins.kt
Update gradle plugin version from 4.2.1 to 4.2.2
NA
**Type**
**Checklist**
=> Update gradle plugin version from 4.2.1 to 4.2.2

datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/validation/PrimitiveTypeAnswerMinLengthValidator.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/validation/RegexValidator.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt, engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt, engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt, reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt, reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt, reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
Fixes #632 
Fix build warnings
NA
**Type**
**Checklist**
=> Fix build warnings

engine/build.gradle.kts, engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt, engine/src/main/java/com/google/android/fhir/MoreDates.kt, engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt, engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt, engine/src/main/java/com/google/android/fhir/db/impl/entities/DateTimeIndexEntity.kt, engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt, engine/src/main/java/com/google/android/fhir/index/ResourceIndices.kt, engine/src/main/java/com/google/android/fhir/index/entities/DateIndex.kt, engine/src/main/java/com/google/android/fhir/index/entities/DateTimeIndex.kt, engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt, engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt, engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt, engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Fixes #597 
**Type**
**Checklist**
=> Create date index table for date without timezone info

engine/build.gradle.kts
Bump up the FHIR engine version to 0.1.0-alpha03
NA
**Type**
Releases
**Checklist**
=> Bump up the FHIR engine version to 0.1.0-alpha03

reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt, reference/src/main/res/values/strings.xml
Fixes #605
Added Sync button Patient list page action bar so that the users can sync resources
**Type**
**Checklist**
=> Add click to sync option into demo app

reference/src/main/assets/screener-questionnaire.json
Fixes #625 
Update temperature, pulse oximetry, pulse heart rate questionnaire item with choice of data types definition 
no
**Type**
Choose one: (Feature)
**Checklist**
=> Questionnaire item with choice of data type definition

datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
Fixes #674 
Choice data type is added value[X] (e.g valueQuantity ...)
Answer is updated to the nested field of choice data type  (e.g Quantity.value, Quantity.code ...)
No
**Type**
**Checklist**
=> Update answers to the choice of data type field.

datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/TypeConversionUtil.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/TypeConversionUtilTest.kt, reference/src/main/assets/screener-questionnaire.json, reference/src/main/java/com/google/android/fhir/reference/ScreenerFragment.kt, reference/src/main/java/com/google/android/fhir/reference/ScreenerViewModel.kt
Fixes #625 
Update vitalsigns questionnaire with code.
no
**Type**
Choose one: (Feature)
**Checklist**
=> vitalsigns questionnaire with code.

reference/src/main/assets/screener-questionnaire.json, reference/src/main/java/com/google/android/fhir/reference/ScreenerViewModel.kt
Fixes #625 
no
**Type**
Choose one: (Feature)
**Checklist**
=> Update symptoms questionnaire as per definition based extraction.

reference/src/main/assets/screener-questionnaire.json, reference/src/main/java/com/google/android/fhir/reference/ScreenerViewModel.kt
Fixes #625 
Add definition extraction url to medical history questionnaire json.
**Type**
Choose one: (Feature)
**Checklist**
=> Update medical history questionnaire json for definition based extraction.

datacapture/build.gradle.kts
Bump up the SDC lib version to 0.1.0-alpha04
NA
**Type**
Release
**Checklist**
=> Bump up the SDC lib version to 0.1.0-alpha04

reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt, reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
Fixes https://github.com/google/android-fhir/pull/691#discussion_r694285443
Remove equals & hashcode from data classes
**Type**
Choose one:Code health 
**Checklist**
=> Removed equals & hashcode from data classes

reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt, reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
Fixes #774 
Country element value was null.
no
**Type**
Bug fix
**Checklist**
=> Reference app crash when country is null.

engine/build.gradle.kts
Bump engine version to 0.1.0-alpha04
NA
**Type**
**Checklist**
=> Bump engine version to 0.1.0-alpha04

reference/src/main/assets/screener-questionnaire.json
Fixes #625 
Add fix for ui alignment issue for below questionnaire.
Symptoms, Medical History.
Include hidden extension to hide questionnaire items.
symptoms, medical history, vital signs.
Modify Risk factors questionnaire json structure  to support definition based resource extraction.
no
**Type**
**Checklist**
=> Screener questionnaire ui alignment issues.

.github/workflows/ci.yml, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Plugins.kt, datacapture/build.gradle.kts, datacapturegallery/build.gradle.kts, reference/build.gradle.kts
Fixes #719 
Added coverage reports for `datacapture` and `datacapturegallery` modules
N/A
**Type**
Choose one: Testing | Code health
**Checklist**
=> Add coverage for SDC + gallery modules and upload to codecov

buildSrc/src/main/kotlin/Dependencies.kt
Fixes NA
**Type**
**Checklist**
=> Upgrade kotlin version to 1.5.31

datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
Fixes #644
Implement population with multiple resources
No
**Type**
N/A
**Checklist**
=> Expression-based population with multiple resources

datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
Remove the unnecessary QuestionnaireItemWithResponse class
Keeping this class around adds nothing to the code
**Type**
**Checklist**
=> Remove the unnecessary QuestionnaireItemWithResponse class

.github/workflows/ci.yml, buildSrc/src/main/kotlin/Plugins.kt, datacapture/build.gradle.kts, datacapturegallery/build.gradle.kts, engine/build.gradle.kts, reference/build.gradle.kts
Upgrade the android gradle plugin from 4.2.2 to 7.0.2
NA
**Type**
**Checklist**
=> Upgrade the android gradle plugin from 4.2.2 to 7.0.2

codegen/build.gradle.kts
=> avoid exposing hapi structs in codegen module

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/LicenseeConfig.kt, datacapture/build.gradle.kts, engine/build.gradle.kts
Will fail our build if non-compliant licenses are added.
Currently allowlisting any dependencies that are non-compliant, so we
can get this plugin enabled. Then we can go back in follow-ups and
decide whether those dependencies need to be removed.
Fixes #758
**Type**
Choose one: (Code health)
**Checklist**
=> Integrate Licensee plugin

.gitignore, README.md
Fixes #[issue number] (I am considering this a trivial and straightforward change, so did not open an Issue
* Formatted README to line-wrap after 80 chars
* Added link to Android Studio Developer site on how to run applications
* Added files to ignore if project is opened using Eclipse or VSCode
**Type**
Choose one: (Bug fix | Feature | **Documentation** | Testing | Code health | Builds | Releases | Other)
**Checklist**
=> Add link and format README + gitignore

engine/src/main/java/com/google/android/fhir/db/impl/entities/UriIndexEntity.kt, engine/src/main/java/com/google/android/fhir/index/entities/NumberIndex.kt, engine/src/main/java/com/google/android/fhir/index/entities/UriIndex.kt, engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt, engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt, engine/src/main/java/com/google/android/fhir/search/filter/UriParamFilterCriterion.kt, engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Fixes #951 
Create the URI filters for the search API
Refactoring included
- Reorder test cases in `SearchTest.kt`
- Rename uri index table column name to be consistent with other tables
**Type**
Feature
NA
**Checklist**
=> Create URI filter for the search API

datacapture/build.gradle.kts
Bump up the version of the SDC lib to 0.1.0-beta01
NA
**Type**
Releases
NA
**Checklist**
=> Bump up the version of the SDC lib to 0.1.0-beta01

gradle/wrapper/gradle-wrapper.properties
Bump version to 7.3.2 ( Adds mitigations for log4j vulnerability)
nil
**Type**
**Checklist**
=> use gradle 7.3.2

datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
Fixes #286
Refactor the questionnaire response validator. Broken the `checkQuestionnaireResponse` function into multiple sub-functions for better structure and readability.
NA
**Type**
Code health
NA
**Checklist**
=> Refactor the questionnaire response validator

buildSrc/src/main/kotlin/Releases.kt, catalog/build.gradle.kts, datacapture/build.gradle.kts, demo/build.gradle.kts, engine/build.gradle.kts, workflow/build.gradle.kts
Extract constant values and licence configurations for libraries and demo apps
**Type**
NA
**Checklist**
=> Extract constant values and licence configurations for libraries and demo apps

datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
Fixes #961 #670 
Refactor the definition-based extraction code by making it more modularized.
NA
**Type**
**Checklist**
=> Refactor the definition-based extraction code

buildSrc/src/main/kotlin/Releases.kt, common/build.gradle.kts
Fixes #1005 
Create the common library release module
NA
**Type**
**Checklist**
=> Use maven publish plugin to release the common module

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Releases.kt, datacapture/build.gradle.kts, engine/build.gradle.kts
Fixes #1005 
The common lib is created in #1015 and will be available in https://maven.google.com/web/index.html?#com.google.android.fhir. This new release will depend on the published artifact instead of using the local module dependency in android studio.
NA
**Type**
**Checklist**
=> Update the dependencies on the common module in the sdc lib and bump version to beta02

catalog/build.gradle.kts
Remove the unnecessary packaging options in the catalog app
NA
**Type**
Code health
**Checklist**
=> Remove the unnecessary packaging options in the catalog app

.github/PULL_REQUEST_TEMPLATE.md
Fairly straight forward, fixes a dead link since the developers guide has been updated
**Type**
Choose one: Other
**Checklist**
=> Update link of the developers guide in PR template

buildSrc/src/main/kotlin/Dependencies.kt, datacapture/build.gradle.kts, datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/LiveBarcodeScanningFragment.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/Utils.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/barcodedetection/BarcodeProcessor.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/camera/CameraSource.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/camera/CameraSourcePreview.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/camera/FrameProcessorBase.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/validation/RegexValidator.kt, demo/build.gradle.kts, demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt, demo/src/main/java/com/google/android/fhir/demo/MainActivity.kt, demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt, demo/src/main/java/com/google/android/fhir/demo/ScreenerViewModel.kt, engine/build.gradle.kts, engine/src/main/java/com/google/android/fhir/FhirServices.kt, engine/src/main/java/com/google/android/fhir/db/impl/SQLCipherSupportHelper.kt, engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt, engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt, engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
Fixes #771
Add [Timber](https://github.com/JakeWharton/timber)  instead of bare android logs. 
**Type**
Code health
**Checklist**
=> Use Timber for logging

datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/barcode/QuestionnaireItemBarCodeReaderViewHolderFactoryInstrumentedTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesTest.kt, engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt, engine/src/test/java/com/google/android/fhir/FhirEngineProviderTest.kt
Fixes #766 
**Type**
**Checklist**
=> imported Truth.assertThat

README.md
Include the HL7 disclaimer in the README.md file as recommended here: http://www.hl7.org/legal/trademarks.cfm?ref=nav
NA
**Type**
Documentation
**Checklist**
=> Include the HL7 disclaimer in the README.md file

CODEOWNERS
Include ktarasenko@ to CODEOWNERS.
**Type**
**Checklist**
=> Include ktarasenko@ to CODEOWNERS.

.github/PULL_REQUEST_TEMPLATE.md
Nit fix. Since folder is called `demo` now, replaced mention of `reference` with `demo`
=> Replace "reference" with "demo" in PR Template

engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt, engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt
Fixes #1212 
Updated code to return `SearchQuery` that contains both query string and arguments.
No
**Type**
**Checklist**
=> Refactored nestedQuery() function to not mutate the passed function args.

buildSrc/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Upgrade Gradle to 7.4.1 and AGP to 7.1.1
NA
**Type**
NA
**Checklist**
=> Upgrade Gradle to 7.4.1 and AGP to 7.1.1

buildSrc/src/main/kotlin/Releases.kt
Bump up the FHIR engine version for the 0.1.0 beta01 release
NA
**Type**
Releases
**Checklist**
=> Bump up the FHIR engine version for the 0.1.0 beta01 release

.allstar/binary_artifacts.yaml
Fixes #1253 
Add binary_artifacts.yaml to opt out of binary artifact check.
This only excludes the repo from the binary artifacts check, not all allstar checks.
NA
**Type**
**Checklist**
=> Add binary_artifacts.yaml to opt out of binary artifact check

buildSrc/src/main/kotlin/Dependencies.kt, workflow/build.gradle.kts, workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt, workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt, workflow/testdata/tests-NotReportable-bundle.json
Fixes #656 
Create the generateCarePlan API in FhirOperator
_NOTE_ the test case is not functioning pending clarification on the local end points.
NA
**Type**
Feature
**Checklist**
=> Create generateCarePlan API in FhirOperator

CODEOWNERS
=> Add wantingzhang as code owner

buildSrc/src/main/kotlin/Releases.kt
Bump up SDC library version number to 0.1.0-beta03
NA
**Type**
Releases
**Checklist**
=> Bump up SDC library version number to beta03

datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
Fixes #1291 
`QuestionnaireItemGroupViewHolderFactory` view binding code is moved to the `QuestionnaireItemHeaderView` as result `localizedHintSpanned` is called on group item and returns text if it has nested display item.
Just return null if localizedHintSpanned get called on group type item.
It also shows extra space in paginated layout for group type.
If question text is empty or null make question textview visibility gone.
**Type**
Before
After
**Checklist**
=> In paginated layout extra display text is shown at the top.

datacapture/build.gradle.kts
Add kotlinTestJunit as test dependency.
**Type**
**Checklist**
=> Add kotlinTestJunit as test dependency in datacapture module.

codelabs/datacapture/app/build.gradle.kts
Trivial change.
Updates placeholder comment for SDC library dependency to latest version, fixes typo.
N/A
**Type**
Documentation
N/A
**Checklist**
=> Update SDC library placeholder to latest version

datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml, datacapture/src/main/res/layout/questionnaire_item_radio_group_view.xml, datacapture/src/main/res/values/styles.xml
Fixes #1441 
- Update Single, Boolean choice selected, non selected state as per figma.
**Type**
Choose one: Feature 
**Checklist**
=> Update single, boolean choice drawables.

catalog/src/main/res/layout/activity_main.xml, catalog/src/main/res/layout/fragment_modal_bottom_sheet.xml, catalog/src/main/res/layout/fragment_questionnaire_response.xml, catalog/src/main/res/layout/landing_page_item.xml, catalog/src/main/res/values-night/themes.xml, catalog/src/main/res/values/styles.xml, datacapture/src/main/res/values/styles.xml
Fixes #1446 
- Datacapture default style has references to material 2 typography.
- Update material3 typography.
**Type**
**Checklist**
=> Update material3 typography.

catalog/src/main/assets/paginated_layout_questionnaire.json
Fixes #1455 
Update questionnaire items with subtitle and flyover text in json.
**Type**
**Checklist**
duct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
=> Update paginated questionnaire json for subtitle and fly over text.

buildSrc/src/main/kotlin/Plugins.kt
Upgrade the AGP version to 7.2.1
NA
**Type**
Builds
NA
**Checklist**
=> Upgrade the AGP version to 7.2.1

buildSrc/src/main/kotlin/DokkaConfig.kt
#1503 accidentally generated docs over the test directories as well, this change restricts to the main directory.
**Type**
Bug fix
**Checklist**
=> Adjust sourceRoots to only include main dir

CODEOWNERS
Add myself as owner to help review code when necessary.
**Type**
Choose one: Other
**Checklist**
=> Add jjtswan@ as an owner

datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogSelectViewHolderFactory.kt
Fixes #1537 
1.  During the binding of ViewHolder, `collect` is called for the particular `SelectedOptionsFlow` based on the questionnaire item's linkid and every `ViewHolder.bind` call results in an additional `collect job `assigned in the viewholder. 
2. This causes issue as the old View holder may be recycled and assigned to a different  questionnaire item altogether and value change in single Item may trigger collect call in multiple view holders (technically every viewholder this particular item was rendered previously).
3. Since `collect` is called inside the `coroutine scope,` the fix is to `cancel` previous `collect job`. 
No …
=> Fix for swapped or cleared answers in Open choice/Drop Down View.

demo/src/main/assets/new-patient-registration-paginated.json
Fixes #1563 
initial value removed for "linkId": "patient-0-gender" from new-patient-registration-paginated.json
**Type**
**Checklist**
=> App crashes when click on edit button on Patient details screen

buildSrc/src/main/kotlin/Releases.kt
=> Bump up engine version to 0.1.0-beta02

gradle/wrapper/gradle-wrapper.properties
Update Gradle version to 7.5.1
NA
**Type**
Builds
**Checklist**
- [x ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
=> Update Gradle version to 7.5.1

engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt, engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
Fixes #1607 
Coding Fhir type added to tokenIndex() function for search
**Type**
**Checklist**
=> Coding Fhir type added to tokenIndex()

README.md, buildSrc/src/main/kotlin/Sdk.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDateTimesTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDatesTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalTimesTest.kt
Fixes #1628 
Support Android API Level 24+
NA
**Type**
Builds
NA
**Checklist**
=> Support Android API Level 24+

buildSrc/src/main/kotlin/Releases.kt
Bump up workflow library version to 0.1.0-alpha02
NA
**Type**
Releases
**Checklist**
=> Bump up workflow library version to 0.1.0-alpha02

datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
Fixes #1802
**Type**
Choose one: Feature 
**Checklist**
=> date format error message updated from 01/01/2023 to 01/31/2023

datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderView.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt, datacapture/src/main/res/values/strings.xml, datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt
Fixes #544 
Remove asterisk for required questions
NA
**Type**
Bug fix
**Checklist**
=> Remove asterisk for required questions

buildSrc/src/main/kotlin/Releases.kt, implementationguide/build.gradle.kts
Bump up SDC lib version number to 1.0.0
NA
**Type**
Releases
**Checklist**
=> Bump up SDC lib version number to 1.0.0

codelabs/datacapture/app/build.gradle.kts, codelabs/datacapture/app/src/main/AndroidManifest.xml, codelabs/datacapture/app/src/main/java/com/google/codelab/sdclibrary/MainActivity.kt
Current codelab code does not build. This change:
* Reverts a change that read sdk/java versions from the main project; the codelab is designed to be the root of the android project and opened in Studio directly
* Completes a partial package refactor that had already been partially implemented.
**Type**
**Checklist**
=> Fix codelab.

codelabs/datacapture/app/src/main/java/com/google/codelab/sdclibrary/MainActivity.kt
Update starter code to match latest codelab.
**Type**
Choose one: Documentation
**Checklist**
=> Update starter code to match latest codelab.

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/RoomSchemaArgProvider.kt, engine/build.gradle.kts, engine/schemas/com.google.android.fhir.db.impl.ResourceDatabase/1.json, engine/schemas/com.google.android.fhir.db.impl.ResourceDatabase/2.json, engine/src/androidTest/java/com/google/android/fhir/db/impl/ResourceDatabaseMigrationTest.kt, engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt, engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt, engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
Fixes #1902 
1. Updated version of db as part of the changed for  #1902 .
2. Added migration for the db.
3. Updated code to export schema (required for tests).
4. Added tests.
No
**Type**
**Checklist**
=> Added migration for the resources db.

buildSrc/src/main/kotlin/Releases.kt
Bump up Engine lib version number to 0.1.0-beta03
**Type**
**Checklist**
=> Bump Engine lib to 0.1.0-beta03

buildSrc/src/main/kotlin/Releases.kt
Fix typos in the artefact description
**Type**
Bug fix 
**Checklist**
=> Fix typos in the knowledge library artefact metadata

license-header.txt
*Description**
Going forward, with each change, the year will shw:
2022-2023
and next year, it will be:
2022-2024
without us doing anything ✨
See public docs for license plugin: https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md#license-header
**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | **Code health** | Builds | Releases | Other)
**Checklist**
=> Make year header dynamic

engine/src/main/java/com/google/android/fhir/sync/Request.kt, engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpDataSource.kt, engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpService.kt, engine/src/main/java/com/google/android/fhir/sync/remote/RetrofitHttpService.kt, engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt, engine/src/main/java/com/google/android/fhir/sync/upload/UploaderImpl.kt, engine/src/main/java/com/google/android/fhir/testing/Utilities.kt, engine/src/test/java/com/google/android/fhir/sync/remote/RetrofitHttpServiceTest.kt, engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
Fixes #2110
* Changed the post method to accept a dynamic URL. This method uses the @Url annotation, allowing it to handle both relative and absolute URLs.
* Remove need for distinct Bundle vs other forms of uploading by generalising the UploadRequest to accept any url and resource (of which Bundle is one) 
**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | **Code health** | Builds | Releases | Other)
**Checklist**
=> Make POST method accept dynamic URL

buildSrc/src/main/kotlin/Releases.kt
Bump engine version to 0.1.0-beta04
NA
**Type**
Releases
**Checklist**
=> Bump engine version to 0.1.0-beta04

workflow-testing/src/main/resources/group-measure/Data-Patients-bundle.json
#2164
Increase the patient date of birth by 1 year to temporarily fix the test case.
The issue should not be closed as a result of this PR. This is **ONLY A TEMPORARY FIX** to unblock other PRs.
An immeidate follow up should be written to fix the test case properly.
I tried using mockk but it didn't work. This is probably because of the java API cql engine uses to retrieve date. We need to try a different method to fix system time.
**Type**
Testing
**Checklist**
=> Increase the patient date of birth by 1 year to temporarily fix the test case

.github/PULL_REQUEST_TEMPLATE.md
=> Fix link to Code of Conduct

catalog/src/main/assets/component_auto_complete.json
Fixes #2174 
Fix initial value and add instruction in auto complete
NA
**Type**
Bug fix
**Checklist**
=> Fix initial value and add instruction in auto complete

.github/actions/commonSetup/action.yml
=> Enable Dependency Graph generation (fixes #2194)

engine/benchmark/build.gradle.kts
=> Remove CQL dependencies in the engine/benchmark module

.github/dependabot.yaml
=> Fix broken dependabot.yaml syntax (fixes #2195)

buildSrc/src/main/kotlin/Releases.kt
Bump up engine version to 0.1.0 beta05
NA
**Type**
Releases
**Checklist**
=> Bump up engine version to beta05

buildSrc/src/main/kotlin/Releases.kt
Bump up the knowledge manager version to 0.1.0 alpha03
NA
**Type**
Releases
**Checklist**
=> Bump up the knowledge manager version to 0.1.0 alpha03

buildSrc/src/main/kotlin/Releases.kt
Bump workflow library version to 0.1.0-alpha04
NA
**Type**
Releases
**Checklist**
=> Bump workflow library version to 0.1.0-alpha04

.github/workflows/build.yml, .github/workflows/codeql.yaml
Fixes #2294
~This is intentionally created only as a DRAFT PR, for now; in order to see if it works, and to compare to other similar changes I'll make; I'll be closing this and/or other such PRs, and in the end keep only 1 of them.~
=> Reduce GitHub Action VM Size to 8-cores · 32 GB RAM · 300 GB SSD 

.github/workflows/build.yml, .github/workflows/codeql.yaml
Reverts google/android-fhir#2307
Due to #2310
=> Revert "Merge CodeQL & Build GitHub Actions (re. #2294)"

buildSrc/src/main/kotlin/Releases.kt
Bump the SDC library release version to 1.1.0
NA
**Type**
Releases 
**Checklist**
=> Bump the SDC library release version to 1.1.0

engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
Missed adding kdoc to the synchronize function in #2385 .
**Type**
Choose one: Documentation
**Checklist**
=> Kdoc for synchronize function post supporting coroutine-safety

buildSrc/src/main/kotlin/Releases.kt
Bump up the release version of engine to 1.0.0
NA
**Type**
**Checklist**
=> Bump up the release version of engine to 1.0.0

engine/src/main/java/com/google/android/fhir/FhirEngine.kt, engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt, engine/src/main/java/com/google/android/fhir/sync/DownloadWorkManager.kt, engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt, engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
**IMPORTANT:** These were largely AI generated! I reviewed but lack context to catch errors. Please review carefully!
Leveraging LLMs to write Kotlin docs for external functions, starting with a few targeted files.
**Type**
Choose one: Documentation
**Checklist**
=> Initial expansion of external function documentation

buildSrc/src/main/kotlin/Dependencies.kt
Remove unnecessary deps
NA
**Type**
**Checklist**
=> Remove unnecessary deps

docs/use/Snapshots.md
small fix on documentation to update link to GitHub Packages
should fix #2579
=> update link to GitHub Packages

engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
Fixes 
The one-time sync operation was not performed sequentially in the test, which caused the syncJobStatus from datastore to be fetched as null. As a result, it was creating the state from WorkManager info, and thus, the test did not fail in the old code
**Type**
**Checklist**
=> Fix Sequential Execution Issue in One-Time Sync Test.

docs/contrib/docs.md
@jingtang10 is this what you were looking for when we last chat about this?
Hope this helps to better explain how this all really works... do shout if there is any aspect missing which you think should also be covered!
@MJ1998 FYI
=> Add more documentation with technical details about how the new website is generated

.github/workflows/codeql.yaml
Fixes #2465
@MJ1998 @jingtang10 please review and merge?
=> Fix obvious typo in codeql.yaml (fixes #2465)

docs/contrib/index.md, engine/build.gradle.kts, knowledge/build.gradle.kts, knowledge/schemas/com.google.android.fhir.knowledge.db.KnowledgeDatabase/1.json, knowledge/src/main/java/com/google/android/fhir/knowledge/db/KnowledgeDatabase.kt
The current `javaCompileOptions` block does not work any more and we need a new `ksp` block.
Also added documentation in the contribution page of the doc site. This may be moved or reorganized in the future as the contribution page grows.
NA
**Type**
Builds
**Checklist**
=> Export database schema in the engine and knowledge modules and add documentation

datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt, datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt, datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesTest.kt
Fixes #2618
**Type**
**Checklist**
=> Create helper function to go through question answer pairs

engine/src/androidTest/java/com/google/android/fhir/db/impl/dao/LocalChangeDaoTest.kt, engine/src/main/java/com/google/android/fhir/db/Database.kt, engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt, engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
=> Small changes for more code readability

buildSrc/src/main/kotlin/Releases.kt, docs/use/api.md
Bump up knowledge manager version to beta01
**Type**
Releases
**Checklist**
=> Bump up knowledge manager version to beta01

docs/contrib/prereqs.md
Update android studio version to Koala and above in documentation, which is compatible with the Android Gradle Plugin (AGP 8.5.0) used in the project. [Ref](https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility)
N/A
**Type**
Documentation
N/A
**Checklist**
=> Update Android Studio version in Prerequisites document

codelabs/datacapture/README.md, codelabs/datacapture/app/build.gradle.kts, codelabs/datacapture/app/src/main/java/com/google/codelab/sdclibrary/MainActivity.kt, codelabs/engine/README.md, codelabs/engine/app/build.gradle.kts, codelabs/engine/app/src/main/java/com/google/android/fhir/codelabs/engine/PatientListFragment.kt, codelabs/engine/app/src/main/java/com/google/android/fhir/codelabs/engine/PatientListViewModel.kt
- SDC
1. Updated the dependencies to latest version.
2. Added callback to Submit button from Questionnaire and removed menu item.
- Engine
1. Updated the dependencies to latest version.
2. Updated code to reflect changed interfaces/classes of engine.
**Type**
**Checklist**
=> Updated the library versions and code in code labs

buildSrc/src/main/kotlin/Dependencies.kt, datacapture/build.gradle.kts, demo/build.gradle.kts, document/build.gradle.kts, engine/build.gradle.kts, gradle/libs.versions.toml, workflow/benchmark/build.gradle.kts, workflow/build.gradle.kts
Update internal dependency on knowledge to beta01
NA
**Type**
Builds
**Checklist**
=> Update internal dependency on knowledge to beta01

buildSrc/src/main/kotlin/Releases.kt, docs/use/api.md
Update workflow library version to beta01
**Type**
Releases
**Checklist**
=> Update workflow library version to beta01

docs/contrib/roadmap.md
Small PR. Commit faea544941d78250b8607f57ddd6d52a95baf5fe moved the location of the contributing file. This PR adjusts sources to changes.
**Type**
Documentation 
**Checklist**
=> Update contributing file reference

demo/src/main/java/com/google/android/fhir/demo/ActivityViewModel.kt, demo/src/main/java/com/google/android/fhir/demo/HomeFragment.kt, demo/src/main/java/com/google/android/fhir/demo/MainActivity.kt, demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt, demo/src/main/java/com/google/android/fhir/demo/extensions/ContextExt.kt, demo/src/main/java/com/google/android/fhir/demo/helpers/PatientCreationHelper.kt, demo/src/main/res/layout/fragment_home.xml, demo/src/main/res/layout/fragment_patient_list.xml, demo/src/main/res/navigation/reference_nav_graph.xml
Fixes #2694 
1. Add hard coded patients to the demo app as default patients.
2. Remove add patient flow.
**Type**
**Checklist**
=> Add hard coded default patients to the demo app.

workflow_demo/src/main/AndroidManifest.xml, workflow_demo/src/main/res/layout/card_item_phase.xml, workflow_demo/src/main/res/layout/fragment_main.xml, workflow_demo/src/main/res/values-night/themes.xml, workflow_demo/src/main/res/values/colors.xml, workflow_demo/src/main/res/values/strings.xml, workflow_demo/src/main/res/values/themes.xml
Used styles similar to engine's Demo app.
**Type**
**Checklist**
=> Update the style to Workflow demo app to look more like other demo apps.

engine/src/main/java/com/google/android/fhir/sync/Sync.kt
Fixes #2695 (in a way)
No tests added as its a trivial change.
**Type**
**Checklist**
=> Make existing work policy configurable in sync apis

buildSrc/src/main/kotlin/Releases.kt, docs/use/api.md
Bump the engine version to 1.2.0
**Type**
**Checklist**
=> Bump the engine version to 1.2.0

buildSrc/src/main/kotlin/Releases.kt, docs/use/api.md
Bump the DataCapture version to 1.3.0.
**Type**
**Checklist**
=> Bump the DataCapture version to 1.3.0

demo/src/main/java/com/google/android/fhir/demo/CrudOperationFragment.kt
Fixes #2774 
Clear the fields on create button is clicked.
**Type**
**Checklist**
=> Clear the fields on create button is clicked.

catalog/src/main/assets/component_auto_complete.json, catalog/src/main/assets/component_auto_complete_with_validation.json, catalog/src/main/assets/component_help.json
Fixes #2781, #2780,#2779
Update the questionnaire json.
**Type**
**Checklist**
=> added fix to prevent the crash in catalog app

datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt, datacapture/src/main/res/layout/questionnaire_fragment.xml, datacapture/src/main/res/values/attrs.xml, datacapture/src/main/res/values/dimens.xml, datacapture/src/main/res/values/strings.xml, datacapture/src/main/res/values/styles.xml
Fixes #1808 
This change adds a title to the review page in Standard Data Capture (SDC) library.
N/A
**Type**
Bug fix
**Checklist**
=> Add review page title
